### ISSUE TITLE
No reaction when copying large directories

### ISSUE THREAD

**Issue by pete3215** [ranger/ranger#806] opened 2017-02-12 08:21 UTC
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: arch linux
- Terminal emulator and version: xterm
- Python version: 3.6
- Ranger version/commit: 1.9.0b4 (also tested on 1.8.1)

#### EXPECTED BEHAVIOR

When copying or moving large files, ranger should keep responding or show that the action is still being performed

#### CURRENT BEHAVIOR

Ranger freezes for several seconds when copying or moving directories with many files.
This behaviour was reproducible with directories containing 1.1 GB of data and several thousand files (mostly source code and compiled binaries)

The time it freezes varies but inm my case it takes up to 10 seconds, giving the impression as if ranger crashed or stoped working. After that it beginns to show the progress bar

#### CONTEXT

It took some time until I realised the copy/move action still works, after waiting some time

#### STEPS TO REPRODUCE

Create a directory with many files

running ranger in debug mode did not change the result or show more information. Ranger did not crash.

**Comment by nfnty** [comment] 2017-02-12 12:32
Duplicate of #151.

**Closed by nfnty** 2017-02-12 12:32 UTC
