### ISSUE TITLE
Code Highlight breaks text preview

### ISSUE THREAD

**Issue by ghost** [ranger/ranger#838] opened 2017-03-20 04:57 UTC
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version:  Nixos Unstable
- Terminal emulator and version:  termite, urxvt, xterm, st
- Python version: 2.7.13
- Ranger version/commit: 1.8.1

#### EXPECTED BEHAVIOR
Preview highlighted code

#### CURRENT BEHAVIOR
Installing ```highlight``` breaks text previews, in effect showing an empty
preview space. Uninstalling ```highlight``` brings back *plain* previews.

#### TRACEBACK
Cant see anything in the log

**Comment by nfnty** [comment] 2017-03-20 13:24
Test running from `master` and update all your config files.

**Comment by hut** [comment] 2017-12-19 21:21
Closing issue because of no reproducibility and idleness of author

**Closed by hut** 2017-12-19 21:21 UTC
Labels: bug, waiting
