### ISSUE TITLE
ueberzug preview sometimes confuses windows

### ISSUE THREAD

**Issue by Battleman** [ranger/ranger#2393] opened 2021-07-13 13:08 UTC
#### Runtime Environment

- Operating system and version: Pop!_OS 20.10
- Terminal emulator and version:  Tilix 1.9.1. Also impacts GNOME Terminal 3.38.0
- Python version: 3.8.10
- Ranger version/commit: 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
When multiple terminals/windows are opened, previewing images with ueberzug sometimes (often) opens the image in an other window, instead of the active one.
![Screenshot from 2021-07-13 14-53-21](https://user-images.githubusercontent.com/6746316/125456452-3ced7d1d-9cbe-4a88-a894-60c884d88786.png)
Above is my 3-screens configuration. While ranger is active in the upper left screen, the image is being rendered in the right screen.

#### Expected Behavior
Images preview should open in the same window as ranger is running

#### Context

I was exploring files when I realized images were not previewed. After pulling my hairs, I realized they were being rendered in another workspace, in a different window.

#### Possible Solutions
No idea. Identifying the window ID and passing that to ueberzug?

#### Steps to reproduce
1.  Install ueberzug
2.  Open multiple terminals
3.  Open ranger in one window, preview an image. Chances are, the image will preview on the other window.

**Comment by toonn** [comment] 2021-07-13 13:21
I wouldn't be surprised if this can't be fixed. @seebye would be able to give a definitive answer though.

**Comment by seebye** [comment] 2021-07-13 20:22
That's not a bug. It works as intended..  
I don't really want to give lessons about theoretical computer science so I'm not going to explain it in detail.  
Every non trivial semantic property of a program is undecidable according to the theorem of rice.  
Thanks to exposed meta data from X11 and the linux kernel it is possible to figure out which window belongs to a tty for programs with certain properties.  
One of these properties is that the program uses one process per window which does not seem to be the case for the terminal emulator you're using.  
So it's only possible to solve this problem for a subset of the set of all programmable terminal emulators.  
So your program isn't in the set of programs for which it's possible to make a correct decision.  

Or to make it short use a terminal emulator which uses one process per window or use another preview method.

**Comment by Battleman** [comment] 2021-07-15 07:35
I was not expecting Rice's theorem to popup in this thread. But yeah, it makes sense. I'm surprised GNOME Terminal also is affected, it doesn't use one process per window? 

> Use another preview method

Unfortunately impossible, Tilix seems [incompatible](https://github.com/gnunn1/tilix/issues/540) with w3m, and the other preview methods require a specific terminal emulator (if I'm not mistaken?)

> Use a terminal emulator which uses one process per window

I'll probably go that way if this becomes too much of a problem. I guess the "usual suspects" (urxvt and kitty) do the trick?

**Comment by toonn** [comment] 2021-07-15 09:22
Kitty, terminology and iTerm2 have native previewing methods, so they tend to be most reliable. There's also an open PR implementing Sixel, testing of that would be very welcome!

**Comment by seebye** [comment] 2021-07-15 10:59
> I'm surprised GNOME Terminal also is affected, it doesn't use one process per window?

Gnome terminal is a daemon terminal all windows belong to the gnome terminal server.  

> I guess the "usual suspects" (urxvt and kitty) do the trick?

Using urxvt is fine if you don't enable its daemon mode.  
Same goes for kitty but if you use kitty you can also use its own preview method.

**Comment by ice-pl** [comment] 2022-01-17 01:18
im using lxterminal and this works
map owt shell $TERMINAL --no-remote & disown
map owr shell nohup $TERMINAL --no-remote -e "unset COLUMNS && unset LINES && ranger" > /dev/null 2>&1 & disown

**Comment by toonn** [comment] 2022-02-27 13:40
I'm closing this because I consider it solved, as being unfixable I guess. Thanks for all the comments!

**Closed by toonn** 2022-02-27 13:40 UTC
Labels: not-our-bug
