### ISSUE TITLE
Chafa output mangled in scope preview

### ISSUE THREAD

**Issue by apetresc** [ranger/ranger#1434] opened 2019-01-08 22:11 UTC
#### Runtime Environment

- Operating system and version: macOS 10.14.2, Arch Linux (tried with both)
- Terminal emulator and version: iTerm 2 3.2.6, termite v14 (tried with both)
- Python version: 3.7.2
- Ranger version/commit: 1.9.2
- Locale: en_US

#### Current Behavior
Chafa's output is mangled in scope previews, as if it doesn't understand the escape codes (even though it works fine directly from the CLI, even in the exact same terminal session):
![](http://screenshot.apetre.sc/2019-01-08-17.06.30.png)

#### Expected Behavior
Using [chafa](https://hpjansson.org/chafa/) as an ASCII image previewer in `scope.sh`, I would expect scope's ASCII image preview to match, more or less, what you get by running `chafa` directly from the CLI, which looks like this:
![](http://screenshot.apetre.sc/2019-01-08-17.04.17.png)

#### Context
It prevents me from using chafa as an image previewer at all, which is a pity, since it is by far the highest-fidelity terminal renderer, and works seamlessly over SSH, any terminal emulator version, etc., which is more than can be said for things like w3m-img.

#### Steps to reproduce
1. Use the following in the `handle_mime()` section of `scope.sh`:
```
# Image
image/*)
    # Preview as text conversion
    chafa "${FILE_PATH}" && exit 4
    exit 1;;
```
2. Open any .png image in ranger's preview pane
3. Compare it visually to the output of directly calling `chafa` and weep :(

I am able to reproduce this on a wide variety of operating systems and terminal emulators, both over SSH and directly. I've also tried messing with a few chaffa parameters, things like using only the upper half-block of UTF-8 symbols for increased compatibility, and it always gets mangled in the same way.

**Comment by toonn** [comment] 2019-01-09 11:41
I suspect this is because ranger doesn't support truecolor. We're at the mercy of the curses (python module) developers when it comes to this alas.
I'd never heard of chafa, what makes you say it's the highest fidelity terminal image viewer? Have you used terminology with its native image previews or kitty with its image protocol, looked into sixel, etc.?

Currently, if you're on a terminal that isn't supported natively, terminology, kitty, iterm2, urxvt to an extent, there is an alternative to w3mimgdisplay in the version of ranger on the master branch, it's called and uses ueberzug, consider trying that.

**Comment by aksh1618** [comment] 2019-01-09 20:00
The issue is also because of all symbols not being supported, as colors can be limited in `chafa`. Maybe using ncursesw could lead to better results? This command currently seems to "work":

```bash
chafa --size="${PV_WIDTH}x${PV_HEIGHT}" --colors 256 --symbols=ascii "${FILE_PATH}" && exit 5
```

**Comment by toonn** [comment] 2019-01-09 23:19
What symbols are not supported? Previews should work just fine with unicode symbols.

**Comment by aksh1618** [comment] 2019-01-10 11:53
It doesn't seem to:
- All symbols enabled in terminal:

![deepinscreenshot_select-area_20190110172110](https://user-images.githubusercontent.com/26065812/50966832-3f6e0600-14fc-11e9-9179-9d9b22d299d5.png)

- All symbols enabled in preview:

![deepinscreenshot_select-area_20190110171512](https://user-images.githubusercontent.com/26065812/50966639-98896a00-14fb-11e9-8b72-76bb60a47352.png)

- Only ASCII enabled in preview:

![deepinscreenshot_select-area_20190110171615](https://user-images.githubusercontent.com/26065812/50966651-a3dc9580-14fb-11e9-9be3-9978b4a97186.png)

**Comment by toonn** [comment] 2019-01-10 14:08
Hmm, weird. Could you determine the exact symbol where it breaks? It's possible the preview doesn't handle things like NUL characters gracefully.

**Comment by hpjansson** [comment] 2019-01-21 15:55
Chafa shouldn't be outputting any nul characters. since those are not used in UTF-8. Maybe there's some kind of conversion that goes wrong afterwards?

As an aside, I strongly recommend --colors 240 over --colors 256, since the lower 16 colors can vary a lot and sometimes look out of place next to the 240-element fixed color cube (e.g. in gradients).

If you want to test without any color codes at all, you can use --colors none. The most widely supported classes for --symbols are ascii, vhalf and block (add +space if you want ASCII spaces too in the two last ones).

If this is an NCurses problem, maybe there is an environment variable set that would let Chafa detect it and pick a compatible mode automatically?

In general, if you find an issue with the Chafa output, feel free to file it at https://github.com/hpjansson/chafa/issues

**Comment by hpjansson** [comment] 2019-02-06 02:19
@aksh1618 Were you testing with Ranger 1.9.2? It has a Unicode handling bug in loader.py that was fixed with f9c49f9c2e7ec680f9a06685eba75787e7d2ed7b. With that applied, `chafa -c 16` works fine as the `scope.sh` image previewer here. That gives you only 16 colors, though.

There is currently no way to support 24-bit color with NCurses, but modern NCurses API supports 65536 color pairs, which is enough for 256 colors (`chafa -c 256`). However! Python's curses module does not support the new API yet.

Here's an example of how a C program was ported to support this: https://github.com/vifm/vifm/commit/7e21fa69a5e78cdbea84b3bb6cf7cf749e99ce8f. Also discussed here: https://github.com/hpjansson/chafa/issues/26

**Comment by apetresc** [comment] 2019-02-11 13:43
Indeed, with current ranger `master`, it looks a lot cleaner with `chafa -c 16`:
![](http://screenshot.apetre.sc/2019-02-11-08.38.44.png)

And despite @hpjansson's warning, it actually looks pretty darn good with `chafa -c 256` too:

![](http://screenshot.apetre.sc/2019-02-11-08.40.58.png)

So I guess I can consider this closed as fixed :)

(On an unrelated note, and maybe this should be a separate issue, but any idea why it's not using the full width it could be using here?)

**Closed** 2019-02-11 13:43 UTC

**Comment by apetresc** [comment] 2019-02-11 13:52
Oh and obviously the width thing is because chafa can't detect the preview pane dimensions by itself. Of course with `chafa -c 256 -s "${PV_WIDTH}x${PV_HEIGHT}" "${FILE_PATH}"` it's:

![](http://screenshot.apetre.sc/2019-02-11-08.48.08.png)

At this size the coloring starts to degrade - it's really weird, at `80x25` the blues are blue and at `160x50` they're all weird mangled and black. I'm gonna chalk that up to the bug @hpjansson was referring to earlier though, and check back on this in a few months when Python's `curses` module catches up.

**Comment by apetresc** [comment] 2019-02-11 14:19
After investigating more closely, yeah, @hpjansson is exactly right that it's the same issue as hpjansson/chafa#26. The reason why the image dimensions matter is because the color pairs get exhausted after a certain point, and that point is reached sooner on larger images.

It even shares the same characteristic of the vifm bug where viewing images in a different order makes a difference. If I view two small images in two different sessions they both look fine, but if I open A first and then B, B will be manged. If B followed by A, then A is mangled. So it is definitely the same underlying issue. Thanks so much to @hpjansson for figuring that one out.

I guess this needs a ticket to be opened against cpython's `curses` module, is that right?

**Comment by toonn** [comment] 2019-02-11 14:31
Feel free to do that, yes. I don't understand why it's taken as long as it has tbh. We would *love* if the fix was backported to 2.6(long shot) or 2.7 though.

**Comment by Crote** [comment] 2019-11-03 23:11
To anyone running into this: it seems like https://github.com/python/cpython/pull/13534 would fix this, but that PR has been open since May without any progress.

**Comment by hpjansson** [comment] 2019-12-09 18:01
I rebased the old Python PR into a new one: https://github.com/python/cpython/pull/17536

**Comment by toonn** [comment] 2022-03-18 12:59
Reading the PR it sounded like it should be transparent curses API-wise.

Note that there's some work to get SIXEL previews in ranger, potentially with a user-specifiable command #2497. This could mean high-fidelity chafa previews in many terminals.

**Comment by hpjansson** [comment] 2022-03-22 22:17
It should be transparent, but the application has to make sure it's not curtailing color indexes somehow. ncurses also has to be built with extended color support, and Python has to detect this support at build time.

There was an [issue report](https://github.com/hpjansson/chafa/issues/77) recently that demonstrates that the sixel and kitty protocols work in vifm. Presumably it's bypassing ncurses. It's a good idea to allow the subprocess access to the tty so it can calculate the number of pixels per cell.
