### ISSUE TITLE
[Bug Report] Mappings (key-command) list gets blocked and removed by `kitty` image preview

### ISSUE THREAD

**Issue by luiz00martins** [ranger/ranger#2672] opened 2022-07-08 13:17 UTC
#### Runtime Environment
- Operating system and version: Pop!_OS 22.04 LTS x86_64
- Terminal emulator and version: zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
- Python version: Python 3.10.4
- Ranger version/commit: ranger-master
- Locale: en_US.UTF-8

#### Current Behavior
The bug happens when the user presses a button that opens the mappings/key-command list (e.g. <kbd>y</kbd>, <kbd>p</kbd>, or <kbd>o</kbd>) while an image preview is being displayed with the kitty previewer.

 1. User puts cursor on top of image file
 2. Image preview loads correctly
 3. User presses a key that opens the key-command list
 4. The image preview starts to reload. The key-command list does not appear, instead waiting for the image to preview reload
 5. key-command list loads together with image (and is overshadowed by it)
 6. Image spontaneously reloads, and list completely disappears
 7. Image keeps reloading itself (with the key-command list still missing) until the user presses <kbd>esc</kbd> 

Video of the current behaviour: [screencast.webm](https://user-images.githubusercontent.com/43142209/177981328-6ea42cee-bfeb-4892-a8b5-deffb0dd10bf.webm)

#### Expected Behavior
 1. User puts cursor on top of image file
 2. Image loads and previews correctly
 3. User presses a key that opens the key-command list
 4. The list loads (without waiting for an image reload)
 5. List stays until the next button press.

#### Steps to reproduce
 1. Have `set preview_images true` and `set preview_images_method kitty`
 2. Open ranger on kitty
 3. Put the cursor in an image which load a preview
 4. Press a key that opens a list of next keypresses (e.g. <kbd>o</kbd>)

**Comment by toonn** [comment] 2022-11-18 09:24
Closing this as a duplicate of #2667. Thank you :heart:  for the more detailed report but that issue seems to be easier to find for people so let's continue discussion there.

**Closed by toonn** 2022-11-18 09:24 UTC
