### ISSUE TITLE
Cannot make a new keybind going to workingdirectory

### ISSUE THREAD

**Issue by TetrisIQ** [ranger/ranger#976] opened 2017-11-24 08:28 UTC
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: Archlinux Kernel: 4.13.12-1
- Terminal emulator and version: Roxterm, Upterm, termite
- Python version: 3.6.3
- Ranger version/commit: 1.8.1
- Locale: de_DE.UTF-8

#### EXPECTED BEHAVIOR
I try to make a new Keybind for going to my actuly workingdirectory.
In ~/.config/ranger/rc.conf I add a line under
'
map gh cd ~ '
'map gw cd ~/Workspace/Projekt/java '
for example.

When I restart ranger, it will display it,  but if I type "gw" nothing happens.
The other Keybindings works fine (for example "gh").

I hope someone can help me.
Thanks

**Comment by toonn** [comment] 2017-12-06 23:20
Have you tried mapping this while ranger is running? (It wouldn't stick but it's useful to test your mappings.)
I just wrote a map for this and as expected it works without a hitch.
Feel free to pop into #ranger on freenode for a (slightly) faster respons : )

**Comment by toonn** [comment] 2018-12-29 19:54
I'm closing because there hasn't been any activity and I couldn't reproduce the issue anyway.

**Closed by toonn** 2018-12-29 19:54 UTC
