### ISSUE TITLE
Sorting of numbers is incorrect

### ISSUE THREAD

**Issue by 0n-Zen** [ranger/ranger#1468] opened 2019-02-10 09:57 UTC
Possibly related to https://github.com/ranger/ranger/issues/1212, but I'm not using setlocal. 

#### Runtime Environment
- Operating system and version: Linux Mint 19 (Tara)
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22 - released: 2016-01-2
- Python version: Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
- Ranger version/commit: ranger-stable 1.8.1
- Locale: LANG=en_US.UTF-8

#### Current Behavior
Sorts numbers (natural):
1
9
10
100
1000
10001
10009
101
1010
1019
102

#### Expected Behavior

Sorts numbers
1
9
10
100
101
102
1000
1001
1009
1010
1019

#### Context
I'm converting video into images. Setting sort to ctime is my current workaround, but then I have to switch sorting back and forth depending on where I am.

**Comment by toonn** [comment] 2019-02-10 15:32
Hmm, I can't reproduce this. For me it goes `100, 101, 1000`.

**Comment by 0n-Zen** [comment] 2019-02-10 19:54
These are the files I'm having trouble with: https://files.catbox.moe/93vzwd.zip
And these are my config files: https://files.catbox.moe/840tqm.zip

**Comment by toonn** [comment] 2019-02-11 00:55
Yeah, they sort fine for me. Just noticed you're running an outdated ranger though so that's probably it.

**Comment by 0n-Zen** [comment] 2019-02-11 19:14
Possible, but I blame updating the OS. I never noticed anything like that back when I ran Mint that was based on ubuntu 14.04.

**Comment by toonn** [comment] 2019-02-11 19:28
It's just because the ubuntu repos are more conservative. Or maybe the package maintainer lost interest in ranger.

Closing this until it's reproduced with the latest version.

**Closed by toonn** 2019-02-11 19:28 UTC
