### ISSUE TITLE
Loader work process failed: Getting preview of

### ISSUE THREAD

**Issue by ycf83** [ranger/ranger#1261] opened 2018-08-16 16:51 UTC
Runtime Environment

    Operating system and version: void linux
    Terminal emulator and version: termite
    Python version: 3.6.6 (default, Jul 16 2018, 09:23:17) [GCC 7.3.0]
    Ranger version/commit: ranger-master 1.9.1
    Locale: en_US.UTF-8

if i want preview image , i get:
Loader work process failed: Getting preview of /......./image.JPG (Percent: 0)

**Comment by flashrunnerGH** [comment] 2018-08-18 21:51
I get the same error while copying files (Loader work process failed: copying files from...).
Manjaro, urxvt, python 3.6.4, ranger 1.9.1
Offtop: Is there any way to show error message untill user interaction and not just few seconds?

**Comment by toonn** [comment] 2018-08-19 11:12
Maybe `W` shows them?

**Comment by ycf83** [comment] 2018-08-20 08:07
whats you means W ??
i try with w3m w3m-img, 
and with mpv method but i get this problem

**Comment by ycf83** [comment] 2018-08-20 14:44
hi, i leave void, switch to ubuntu and all work great, thnk's for help

**Comment by toonn** [comment] 2018-08-20 20:32
We'll keep this open for @flashrunnerGH.
By `W` I meant pressing `W` while in ranger.

**Comment by flashrunnerGH** [comment] 2018-08-21 19:47
I've found a problem. There was a "special" file in a list somehow (tried to backup dot files). 
`w` is good, but I'm not 100% satisfied with it, because when I copy a long list of files and go AFK, I can even not know that there was a problem, because most of the files were successully copied.

**Comment by toonn** [comment] 2018-08-21 20:11
Tbh, for anything involving data I don't want to lose or long operations I stick to battle tested programs like rsync for instance.

I think it would be possible to add a setting for notification duration. It would be a lot harder to detect absence of interaction and automatically keep them around until the user interacts.

**Comment by toonn** [comment] 2018-08-21 23:02
That would be possible (showing the last message instead of just a character) if the duration was configurable as a setting.

**Comment by sseneca** [comment] 2019-03-19 21:19
Hiya, image previews work for me but video previews do not. I enabled them following [this](https://github.com/ranger/ranger/wiki/Video-Previews), but now whenever I focus on a video I get:

![image](https://user-images.githubusercontent.com/25619071/54642358-4bda8600-4a8c-11e9-9551-f3c036947880.png)

I'm running Arch Linux, kernel version 5.0.2-arch1-1-ARCH. Ranger info:
```
ranger version: ranger 1.9.2
Python version: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
Locale: en_GB.UTF-8
```

**Comment by toonn** [comment] 2019-03-19 22:44
@sseneca, could you try running the master version of ranger? For arch it's in the AUR as ranger-git or ranger-git-master or something. Or, you could just clone the repo and run `repo/ranger.py`.

**Comment by sseneca** [comment] 2019-03-19 22:50
@toonn, progress! This no longer gives me an error message, but outputs something weird, which you can see below.

![image](https://user-images.githubusercontent.com/25619071/54647046-06708580-4a99-11e9-8181-e8634ee9cd89.png)

**Comment by IonVucv** [comment] 2019-03-20 00:08
@sseneca 
Are both these line uncommented in .config/ranger/scope.sh?
![pic-selected-190320-0206-28](https://user-images.githubusercontent.com/48133834/54649942-20fc2c00-4aa4-11e9-8eb4-ca8023279a98.png)

**Comment by sseneca** [comment] 2019-03-20 00:26
I just checked my `scope.sh` and -- whist I had uncommented the video-related code -- the version I had must have been old (it was from the `ranger` version from the community repos). I deleted it and re-ran `ranger --copy-config=scope`, and then uncommented these lines. Now things seem to be working! Thanks.

**Comment by LinArcX** [comment] 2019-12-01 16:27
I have same issue when i want to see the preview of text files.
Os: void linux (It's updated)
And also i replace newer version of scope.sh with my old one. but still have this issue.

**Comment by fabriziobertoglio1987** [comment] 2020-01-18 18:44
I had this issue

fact is if you press `W` while in ranger after receiving the error message you get the full log

it was a permission error

**Comment by Amooti73** [comment] 2020-05-02 07:31
After installing the master branch of ranger, the problem persisted.  Finally I made this symlink:

`sudo ln -s /usr/lib/python3/dist-packages/chardet /usr/lib/python3.8/chardet`

It seems to have worked as a workaround.  I am on Ubuntu 20.04

**Comment by toonn** [comment] 2020-05-02 07:45
Since there's been multiple reports now of solutions to this that aren't under ranger's control I'm going to close the issue. Feel free to reopen if you've tried everything in this thread and the problem still persists.

**Closed by toonn** 2020-05-02 07:45 UTC
Labels: bug

**Comment by Amooti73** [comment] 2020-05-02 08:08
OK, thanks!  I wish I could have been more helpful to ranger! It is
probably the most useful program I can think of! 

* Toon Nolten <notifications@github.com> [2020-05-02 00:45:59 -0700]:

>Since there's been multiple reports now of solutions to this that aren't under ranger's control I'm going to close the issue. Feel free to reopen if you've tried everything in this thread and the problem still persists.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ranger/ranger/issues/1261#issuecomment-622813429

-- 
Bro. John Flood, C.S.C.
McCauley Formation House
Congregation of Holy Cross
P.O. Box 940-00502 Karen
Nairobi, Kenya

Email: jfloodcsc@gmail.com
jflood@cuea.edu
Phone: +254-711-983025/0711-983025
+256-779-427935

Jesus "expects us to stop looking for those personal or communal niches which shelter us from the maelstrom of human misfortune, and instead to enter into the reality of other people's lives and to know the power of tenderness.  Whenever we do so, our lives become wonderfully complicated".

Pope Francis, The Joy of the Gospel, 44

**Comment by masabbat** [comment] 2020-08-02 17:24
Worked for me too on alpine linux.

sudo ln -s  /usr/lib/python3.8/site-packages/chardet /usr/lib/python3.8/chardet

Many thanks.

**Comment by vortexnix** [comment] 2022-01-19 11:42
At least in my case, the issue occurs when the directory to be copied contains one or more broken symlink

**Comment by toonn** [comment] 2022-02-27 13:53
@vortexnix, could you formulate reproducible steps? I tried making a broken symlink and copying it and its containing directory around a bit and I didn't experience any issues.
