### ISSUE TITLE
no image show if i don't resize the terminal after update

### ISSUE THREAD

**Issue by yadex** [ranger/ranger#1860] opened 2020-03-01 01:36 UTC
#### Runtime Environment

- Operating system and version:  ArchLinux
- Terminal emulator and version: Urxvt
- Python version: 3.8
- Ranger version/commit: 1.9.3
- Locale: en_US

#### here is a gif 
![1](https://user-images.githubusercontent.com/20081672/75617885-172de480-5ba0-11ea-8fc2-ffc5c1c36d95.gif)

**Comment by toonn** [comment] 2020-03-01 12:22
Is this with the w3m or the urxvt method? Gonna need a lot more information to even be able to start looking into this.

**Comment by Paul-Houser** [comment] 2020-03-02 19:50
Same issue here. Using the w3m method in rxvt-unicode terminal. Arch linux kernel 5.5.7

**Comment by hovnatan** [comment] 2020-03-03 07:19
Same issue here. Using the w3m method in termite terminal.

**Comment by toonn** [comment] 2020-03-03 07:37
So far the commonality is that you're using the `w3m` method in terminals that aren't "like xterm" enough for `w3mimgdisplay` to work properly. They explicitly only support XTerm.

You can try one of the other methods, like `urxvt` or `ueberzug`.

**Comment by hovnatan** [comment] 2020-03-03 08:37
Both `urxvt` and `ueberzug` don't work for me on Arch Linux with latest updates. I use termite.

**Comment by toonn** [comment] 2020-03-03 08:59
@hovnatan, well `urxvt` only works in urxvt. `ueberzug` should work for you if you install the dependency `ueberzug`, install using pip, not the AUR.

**Comment by hovnatan** [comment] 2020-03-03 10:44
For `ueberzug` I get `[Errno 13] Permission denied 'ueberzug'`.

**Comment by toonn** [comment] 2020-03-03 13:25
@hovnatan, that doesn't have anything to do with ranger, you'll need to figure that out on your own. Check the ueberzug README for install instructions.

**Comment by Paul-Houser** [comment] 2020-03-03 17:37
The w3m method was working for me just fine in urxvt up until 2 days ago after a full system upgrade, and it stopped working on both of my pc's at the same time. The upgrade was to arch linux 5.5.7, along with a few other updates but I don't recall which ones.

**Comment by Paul-Houser** [comment] 2020-03-03 17:39
@hovnatan permission denied errors almost always means you need to run it with `sudo` for it to work

**Comment by toonn** [comment] 2020-03-03 18:05
I wouldn't advise running ranger or ueberzug as root/using sudo.

**Comment by Paul-Houser** [comment] 2020-03-03 18:29
Trying not to go too off topic here but `[Errno 13] Permission denied` is a pip error that occurs if you don't run `pip` with sudo. Unless I misunderstood he was having trouble installing it.

**Comment by hovnatan** [comment] 2020-03-04 03:20
Actually after the latest commits image display started working in `termite` with `w3mimgdisplay`.

**Comment by Paul-Houser** [comment] 2020-03-04 05:33
Same for me. Issue solved I guess haha

**Comment by toonn** [comment] 2020-03-04 10:29
Really? That's weird, I don't remember any changes to image previews since release 1.9.3. Did Termite or w3mimgdisplay get updated maybe?

**Comment by osalas88** [comment] 2020-06-11 22:40
I have exactly the same problem as described in this thread but I'm using a different terminal and method.

Operating system and version: ArchLinux
Python version: 3.8
Ranger version/commit: 1.9.3
Terminal: `kitty 0.17.4` (also tried `st` and `urxvt`)
Image preview method: `ueberzug`

for all the terminals I tried the issue was the same, no image at first then after resizing the window the preview was working without any further issues for all images.

My assumption was that my window manager was not feeding the proper window/terminal position and then the resize was updating it but tried different window managers and the issue remained. (tested with i3, bspwm and openbox)

I also tested ueberzug with the following script and works as intended, no need to resize the window for the image to appear

```
#!/usr/bin/bash

source "`ueberzug library`"


ImageLayer 0< <(
	ImageLayer::add [identifier]="test0" [max_width]="200" [max_height]="200" [x]="0" [y]="0" [path]="$1"
    sleep 10
)
```

**Comment by toonn** [comment] 2020-06-12 08:36
Since the OP hasn't provided any more information and everyone else in the thread doesn't have the issue anymore I'm going ahead and closing this. Thank you to everyone who provided some details that might help others who run into the same problem!

**Closed by toonn** 2020-06-12 08:36 UTC
Labels: image-preview

**Comment by ReneganRonin** [comment] 2020-11-17 07:49
> @hovnatan, well `urxvt` only works in urxvt. `ueberzug` should work for you if you install the dependency `ueberzug`, install using pip, not the AUR.

i tried installing it with pip after `paru -Rsc ueberzug` but it still reproduces the same behavior.

**Comment by ReneganRonin** [comment] 2020-11-17 08:16
> I have exactly the same problem as described in this thread but I'm using a different terminal and method.
> 
> Operating system and version: ArchLinux
> Python version: 3.8
> Ranger version/commit: 1.9.3
> Terminal: `kitty 0.17.4` (also tried `st` and `urxvt`)
> Image preview method: `ueberzug`
> 
> for all the terminals I tried the issue was the same, no image at first then after resizing the window the preview was working without any further issues for all images.
> 
> My assumption was that my window manager was not feeding the proper window/terminal position and then the resize was updating it but tried different window managers and the issue remained. (tested with i3, bspwm and openbox)
> 
> I also tested ueberzug with the following script and works as intended, no need to resize the window for the image to appear
> 
> ```
> #!/usr/bin/bash
> 
> source "`ueberzug library`"
> 
> 
> ImageLayer 0< <(
> 	ImageLayer::add [identifier]="test0" [max_width]="200" [max_height]="200" [x]="0" [y]="0" [path]="$1"
>     sleep 10
> )
> ```
> 
> Update: I was going over some other bugs and found out that it was actually my shell.
> I'm using fish-shell and decided to update to the fish-git and this solved the problem for me.
> I see from the gif that the command is autocompleted so I believe fish was being used.

I followed the quoted message above. After installing fish from the AUR which is `fish-git` rather than installing it from the official arch repositories, image previews worked flawlessly. weird.... idk what really messed the image previews when using fish from the official arch repos.

**Comment by toonn** [comment] 2020-11-17 09:24
There's a fish bug that has been fixed but isn't available in a release yet.
