### ISSUE TITLE
Analog of Ctrl-O from Midnight Commander

### ISSUE THREAD

**Issue by agornushkin** [ranger/ranger#842] opened 2017-03-30 12:20 UTC
Maybe its already implemented, but could not find in the documentation

Is it now possible to switch to console in the current directory, and then switch back?
Midnight Commander does this on Ctrl-O by default.

Current alternatives I found:
Stopping by Ctrl-Z: Not so good, because it  sends you back to directory where you were when you had started ranger.
Firing `:shell bash` : Not so good when you often switch back and forth, as you lose your environment variables.

**Comment by nfnty** [comment] 2017-03-30 14:46
Have you tried using tmux?

**Comment by Vifon** [comment] 2017-03-30 23:48
That's exactly what my [texas](https://github.com/vifon/texas) tries to accomplish with tmux and some sorcery. Please check if it is a viable solution for you.

**Comment by agornushkin** [comment] 2017-03-31 06:42
@Vifon, thanks a lot, thats exactly the functionality I wanted to find/ask for in ranger.

**Comment by Vifon** [comment] 2017-04-01 19:01
I'm closing the issue. If you find the solution insufficient, please reopen it.

**Closed by Vifon** 2017-04-01 19:01 UTC
Labels: question

**Comment by cpchan** [comment] 2019-08-17 03:11
I would like to reopen this issue. The problem is that with solutions like texas  and zranger is that that are all tmux based. The problem is that tmux does not support graphically previews. So far I have tried all of the preview methods (with the exception of iterm2) in the appropriate terminal apps with no success. Preview show up in regular ranger, but not in zranger which falls back to metadata.

**Comment by toonn** [comment] 2019-08-17 11:58
Afair tmux supports image previews with w3m and kitty at least. Also terminology and urxvt I believe. Though I can't speak for zranger.

It's not quite clear to me what you want but if what you want is a shell synchronized with a ranger instance than I'm afraid you're out of luck. There's no great solution currently and I'm not sure there can be. Synchronizing ranger's directory with that of a subshell is hard for example, same thing for retaining the environment between subshells. (Maybe direnv can help there?)

**Comment by cpchan** [comment] 2019-08-17 13:27
Toon Nolten <notifications@github.com> writes:

Hello Toon,

> Afair tmux supports image previews with w3m and kitty at least. Also
> terminology and urxvt I believe. Though I can't speak for zranger.

After some testing the w3m method (ugly hack) does work in tmux (with all
supporting terminals), but not in zranger, which only shows the
metadata.

Both the Terminology and Kitty methods fail within tmux.

> It's not quite clear to me what you want but if what you want is a
> shell synchronized with a ranger instance than I'm afraid you're out
> of luck. There's no great solution currently and I'm not sure there
> can be. Synchronizing ranger's directory with that of a subshell is
> hard for example, same thing for retaining the environment between
> subshells. (Maybe direnv can help there?)

Yes, this is what I wish for. A mini command line buffer, like in all
Norton inspired file managers, is a bonus.

Charles

**Comment by cpchan** [comment] 2019-08-17 20:24
After the author of zranger suddenly remembered that he intentional disabled graphical previews because: "Graphical previews based on w3m won't work properly when you detach tmux from the original terminal and attach to it from a new one, which is exactly what zranger does in a nutshell." After changing zranger to enable graphical previews, now everything is working. I am using the ueberzug method for previews.

I can now move back to Yakuake which is my terminal of choice. I really don't like Terminology.

**Comment by Vifon** [comment] 2019-08-17 21:04
Yeah, sorry about that, @cpchan. ^^

**Comment by cpchan** [comment] 2019-08-17 21:48
@Vifon, no problem. I am just glad that I got it working. BTW, I just tried Texas, however, the display keeps messing up when I move around the Miller columns.

**Comment by Vifon** [comment] 2019-08-17 22:30
Try resizing the terminal window. Ranger might get confused about the initial window size due to some race conditions.

**Comment by toonn** [comment] 2019-08-17 22:48
@cpchan vice versa for me re terminals : )
