### ISSUE TITLE
Crash when using 'find' and typing certain letters

### ISSUE THREAD

**Issue by ngoonee** [ranger/ranger#2136] opened 2020-10-26 06:44 UTC
This only happens on ranger-git. ranger 1.9.3 in the Arch repos doesn't show this behaviour.

#### Runtime Environment

- Arch Linux
- Alacritty (happens in termite too)
- Python version: 3.8.6
- Ranger version/commit: 1.9.3.101.g57127d53
- Locale: en-GB

#### Current Behavior
Pressing 'f' and then typing some folder names (not others) just crashes ranger as in the traceback below. Can't seem to find a pattern on what names trigger this, but once I know a folder does, I can repeat it all the time (even with ranger --clean).

#### Expected Behavior
No crashes

#### Steps to reproduce
1. Start ranger, browse to any folder.
2. Press 'f' to start 'find'
3. Start typing the name of a folder (in my case, I type 'w' in a folder with 6 sub-folders (Church, Code, Finance, Home, Media, Work) which is supposed to open the Work folder)

#### Traceback

```
$ ranger --clean                                                          (ai)
ranger version: ranger-master
Python version: 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Locale: en_GB.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.8/site-packages/ranger/config/commands.py", line 1521, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.8/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.8/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.8/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.8/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.8/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Oxore** [comment] 2020-11-14 22:56
Hello. I think I've managed to find out a way to reproduce the crash.

This behavior may be triggered with a symlink or a hardlink pointing anywhere and placed in the directory, that has such attributes, that it ends up being not the first in a list of directories sorted by current `ranger`'s sorting settings.

# Steps to reproduce

Assume sorting settings are `sort natural` and `sort_reverse false`.

1. Create the following tree of nested directories and put a symlink in one of it. I did everything in `/tmp`:

```
mkdir -p /tmp/dir/{a,ab}
ln -s / /tmp/dir/ab/symlink
```

2. Run `ranger` in `/tmp/dir`:

```
ranger /tmp/dir
```

3. At that point we've landed on directory `a` and we have a chance to trigger the bug using the `f`ind feature to move into `ab` directory. In other words, just press `f` and type `ab`. And we got a crash with a stacktrace:

```
ranger version: ranger-master
Python version: 3.7.9 (default, Nov 12 2020, 05:51:07) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/usr/lib/python3.7/site-packages/ranger/config/commands.py", line 1520, in execute
    self.fm.move(right=1)
  File "/usr/lib/python3.7/site-packages/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/usr/lib/python3.7/site-packages/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/usr/lib/python3.7/site-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.7/site-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.7/site-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.7/site-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object is not subscriptable

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by Rom1deTroyes** [comment] 2020-11-14 23:33
Same here with python2, following this 3 last steps, here is my report (TypeError slightly differs) :
```
ranger version: ranger-master v1.9.3-104-ge4d2f6ec
Python version: 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Locale: None.None

Traceback (most recent call last):
  File "/home/romain/src/Ranger/ranger/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/home/romain/src/Ranger/ranger/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/home/romain/src/Ranger/ranger/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/home/romain/src/Ranger/ranger/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/home/romain/src/Ranger/ranger/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/home/romain/src/Ranger/ranger/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/home/romain/src/Ranger/ranger/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/home/romain/src/Ranger/ranger/ranger/gui/widgets/console.py", line 514, in on_line_change
    self.execute(cmd)
  File "/home/romain/src/Ranger/ranger/ranger/gui/widgets/console.py", line 454, in execute
    cmd.execute()
  File "/home/romain/src/Ranger/ranger/ranger/config/commands.py", line 1521, in execute
    self.fm.move(right=1)
  File "/home/romain/src/Ranger/ranger/ranger/core/actions.py", line 499, in move
    self.thistab.enter_dir(tfile)
  File "/home/romain/src/Ranger/ranger/ranger/core/tab.py", line 183, in enter_dir
    self.thisfile = self.thisdir.pointed_obj
  File "/home/romain/src/Ranger/ranger/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/home/romain/src/Ranger/ranger/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/home/romain/src/Ranger/ranger/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/home/romain/src/Ranger/ranger/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
TypeError: 'NoneType' object has no attribute '__getitem__'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

If you reload ranger after the crash, and press <kbd>'</kbd>, your <kbd>'</kbd> bookmark points to `/tmp/dir/ab`, and then if you press <kbd>'</kbd> to go there, ranger opens the listing of `/tmp/dir/ab/symlink/` in the right pane, and an error message says :
  Bad arguments for enter_bookmark: ["'"], {}

At this point, if you get back to `/tmp/dir/`, <kbd>f</kbd><kbd>ab</kbd> is working.

investigations made with :

- ranger version: ranger-master v1.9.3-125-gaa5495e4
- Python version: 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
- Locale: None.None

and

- ranger version: ranger-master v1.9.3-125-gaa5495e4
- Python version: 3.7.3 (default, Jul 25 2020, 13:03:44) [GCC 8.3.0]
- Locale: fr_FR.UTF-8

**Comment by Oxore** [comment] 2020-11-15 00:54
I've narrowed it down a little.

If you have stepped on a directory previously just moving by `j` and `k`, then ranger won't crash when you are trying to get into that directory via `f`ind. Otherwise it will.

Or when typing directory name it must have such an ambiguous name, that when you type a part of it the cursor land on it, but not enter until more letters of the name are specified. So it becomes kind of "visited" and then entering it won't produce the crash. For example, consider the following directory structure:

```
./a/
./bb/file
./bc/file
```

Typing `f` followed by `b` in ranger will land us on directory `bb` and by typing another `b` ranger will enter the `bb` directory. If we type `c` instead of second `b` ranger will crash.

And `bb` must have at least one file of any type (not necessarily a symlink). If it does not have any files, then ranger will crash anyway, but with different error: `IndexError: list index out of range`. This is probably not related. Maybe create another issue about it?

**Comment by mrjoedang** [comment] 2020-11-17 16:20
Same issue:
`OS: Pop!_OS 20.04 LTS x86_64 `
```
ranger version: ranger-master 
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) [GCC 9.3.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/local/lib/python3.8/dist-packages/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/local/lib/python3.8/dist-packages/ranger/config/commands.py", line 1546, in quick
    self.fm.thisdir.refilter()
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/local/lib/python3.8/dist-packages/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/local/lib/python3.8/dist-packages/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/local/lib/python3.8/dist-packages/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Closed** 2021-01-05 19:05 UTC
Labels: bug

**Comment by ixzh** [comment] 2021-01-15 19:38
fsud will crash the programme when the last d is typed..

**Comment by toonn** [comment] 2021-01-15 20:59
This was fixed on master.

**Comment by ixzh** [comment] 2021-01-16 04:44
I'm using on Manjaro
![image](https://user-images.githubusercontent.com/14981695/104797383-95b36500-57f8-11eb-9617-c4a31fed5142.png)

Maybe not the latest version?

**Comment by toonn** [comment] 2021-01-16 11:39
@ixzh, yes that's more than 20 commits old. They should really offer official releases under the name ranger and offer more recent commits under an alternative name, "ranger-master" or "ranger-git" for example.
You might also want to replace your `scope.sh` with the one from the official repo because last time I checked manjaro includes a really old one.
