### ISSUE TITLE
small bug when suspending ranger from within vim

### ISSUE THREAD

**Issue by rnmhdn** [ranger/ranger#1903] opened 2020-04-07 12:14 UTC
1. open ranger
1. open a file with vim
1. press `^Z`
1. fg
1. ranger looks unresponsive but it is not
1. `:q` to go back to ranger
1. `^L` to redraw and see everything again.

**Comment by toonn** [comment] 2020-04-07 17:03
Can confirm not sure what the problem is. I'd expect vim is responsible for redrawing at that point.

**Comment by doak** [comment] 2021-03-20 23:02
Probably duplicate/related to #160 (and others), though discussion seems to be bundled there.

**Comment by toonn** [comment] 2021-03-21 13:27
@doak, thanks for pointing this out! Closing as duplicate.

**Closed by toonn** 2021-03-21 13:27 UTC
Labels: bug
