### ISSUE TITLE
OSX issue with image preview,

### ISSUE THREAD

**Issue by EvanCarroll** [ranger/ranger#1510] opened 2019-03-27 22:48 UTC
When I try to open an image with OSX, I'm getting,
```

Warning: Unable to set locale.  Expect encoding problems.
ranger version: ranger 1.9.2
Python version: 3.7.2 (default, Dec 30 2018, 08:55:50) [Clang 10.0.0 (clang-1000.11.45.5)]
Locale: None.None

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
Evan-Carrolls-MBP:~ evancarroll$ ranger --version
```

**Comment by toonn** [comment] 2019-03-28 10:22
What do you mean when you say "open?" Triggering it, with right arrow or `l`? Just scrolling through the directory?

Also, you seem to be missing locale setup. What's the output when you run `locale`? I had similar issues but I don't remember how I fixed them : / here's the output for my locales though:

```
LANG=
LC_COLLATE="C"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by EvanCarroll** [comment] 2019-03-28 13:17
open means `ranger foo.png` 

My locale is currently,

```
LANG="en_US.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL="C"
```

**Comment by toonn** [comment] 2019-03-28 14:24
Oh, wait, this is a known bug. Not specific to images but any file. I'll close this as a duplicate when I come across that one.

**Comment by hut** [comment] 2019-04-03 16:07
This is a duplicate of #1386. Just fixed it. If it still doesn't work for you, please reply in #1386.

**Closed by hut** 2019-04-03 16:07 UTC
Labels: duplicate
