### ISSUE TITLE
core.loader: Unaligned stream reading causes decode errors

### ISSUE THREAD

**Issue by beanaroo** [ranger/ranger#522] opened 2016-04-05 22:08 UTC
Error shown is:

```
decode() Argument 1 must be str, not none
```

I noticed changing the extension to `.txt` allows preview/paging. I'm guessing it's a syntax highlighting thing?
I confirmed the document isn't tainted by using `iconv`.

```
ranger version: 1.7.2, executed with python 3.5.1
Locale: en_NZ.UTF-8
Current file: /home/bean/documents/studies/tech/networking/Cisco/CCENT/notes/02-Models_of_Interconnection.md
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 260, in safeDecode
    return string.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 511: unexpected end of data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 143, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 342, in loop
    loader.work()
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 400, in work
    self.fm.notify(err)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 394, in work
    next(item.load_generator)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 204, in generate
    read = safeDecode(read)
  File "/usr/lib/python3.5/site-packages/ranger/core/loader.py", line 263, in safeDecode
    return string.decode(chardet.detect(string)["encoding"])
TypeError: decode() argument 1 must be str, not None
```

File in question: [02-Models_of_Interconnection.md.txt](https://github.com/hut/ranger/files/205415/02-Models_of_Interconnection.md.txt)

**Comment by hut** [comment] 2016-04-15 13:20
Is that with ranger 1.7.2 stable, e.g. from some package management system, or do you use the master-branch from git?

**Comment by beanaroo** [comment] 2016-04-15 14:05
I'm using ranger-git from the Arch User Repositories. Package manager lists version as `1.7.2.237.g65b9bce`, updated a few hours ago. Double checked to see if it's still reproducible and it actually happens on multiple markdown files.

I believe it might be worth mentioning these are written using [pandoc](http://pandoc.org/README.html#pandocs-markdown)'s implementation. To be honest, I haven't had a chance to look at how ranger's preview system works. Will investigate more in the morning.

**Comment by hut** [comment] 2016-04-15 14:31
Oh wait, I can actually reproduce it.

So the problem is that when previewing, ranger reads a certain number of characters from the stream. Sometimes it stops reading just before a multi-byte unicode character is finished. Attempting to decode that incomplete unicode character causes that crash, which I now fixed. The underlying problem that the reads should be aligned to unicode characters is still unsolved though.

**Comment by nfnty** [comment] 2017-01-29 19:07
@beanaroo Are you still having this issue on `master`?

**Comment by beanaroo** [comment] 2017-02-02 22:38
@nfnty I am no longer getting the issue described, thank you!

**Closed** 2017-02-02 22:38 UTC
Labels: bug
