### ISSUE TITLE
crash after pressing Mi

### ISSUE THREAD

**Issue by sukovanej** [ranger/ranger#847] opened 2017-04-05 08:36 UTC
This had happened after I pressed "Mi" combiation.

```
ranger version: 1.8.1, executed with python 3.6.0
Locale: cs_CZ.UTF-8
Current file: /home/suk/Projects/vibed/vibed
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 168, in draw
    self._draw_directory()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 348, in _draw_directory
    infostringdata = current_linemode.infostring(drawn, metadata)
  File "/usr/lib/python3.6/site-packages/ranger/core/linemode.py", line 107, in infostring
    fileinfo = fileinfo.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode' 
```

**Comment by zyklotomic** [comment] 2017-04-05 08:57
Can confirm for 1.8.1, but it appears patched in latest (git). Try the latest build straight from the repo.

**Comment by nfnty** [comment] 2017-04-05 09:56
Duplicate of #800. Already been fixed.

**Closed by nfnty** 2017-04-05 09:56 UTC
Labels: bug, duplicate
