### ISSUE TITLE
Ranger Crashed. ValueError: Color number is greater than COLORS-1 (7).

### ISSUE THREAD

**Issue by dav1ta** [ranger/ranger#2583] opened 2022-03-03 15:24 UTC
## Ranger TraceBack
ranger crashes when previewing this file
[https://dwm.suckless.org/patches/scratchpad/dwm-scratchpad-6.2.diff](url)

```
ranger version: ranger 1.9.3
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
Locale: en_US.UTF-8
Current file: '/home/mate/dwm-6.3/dwm-scratchpad-6.2.py'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

## Terminal St
color configuration if needed.
```
/ Terminal colors (16 first used in escape sequence) /
static const char *colorname[] = {
    / 8 normal colors /
    "#282828", // dark
    "#cc241d", // red
    "#98971a", // yellow
    "#d79921", // orange
    "#458588", // blue
    "#b16286", // purple
    "#689d6a", // green
    "#a89984", // bronze

    / 8 bright colors /
    "#928374",
    "#fb4934",
    "#b8bb26",
    "#fabd2f",
    "#83a598",
    "#d3869b",
    "#8ec07c",
    "#ebdbb2",

    [255] = 0,

    / more colors can be added after 255 to use with DefaultXX /
    "#ebdbb2",
    "#b9b9b9",

};


/*
 * Default colors (colorname index)
 * foreground, background, cursor, reverse cursor
 */
unsigned int defaultfg = 7;
unsigned int defaultbg = 0;
unsigned int defaultcs = 256;
static unsigned int defaultrcs = 257;
```

**Comment by Gregaras** [comment] 2022-03-03 15:33
Seems to be same error: https://github.com/ranger/ranger/issues/2524

**Comment by GissingValeska** [comment] 2022-04-12 06:07
how to solve this problem，my terminal is iTerm2

**Comment by nadapez** [comment] 2022-04-13 00:54
The problem is that the exception is supposed to be catched but the try clause expects a curses.error exception which is different from the actual exception raised: ValueError.

I suppose is due to a change in curses package.

Solution for version 1.9.3: change the lines https://github.com/ranger/ranger/issues/32 and https://github.com/ranger/ranger/issues/44 in color.py from except curses.error: to except (curses.error, ValueError):

**Comment by AlexiWolf** [comment] 2022-04-20 23:57
I'm having a similar issue, when previewing Markdown files with links in them.  Markdown files without links do not trigger the crash.  I can also confirm diff files will also trigger the problem.  Here's some additional background, and steps I've found to trigger the problem. 

#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: alacritty 0.10.0-dev (a1083d18)
- Python version: Python 3.9.2
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

Ranger crashes when previewing markdown files with links in them.

#### Expected Behavior

Ranger should display a highlighted preview of markdown files.

#### Steps to reproduce
1. Create a `test.md` file.
2. Add a link to the MD file:
```Markdown
[a link](example.com)
```
3. Open ranger, and navigate over the file.
4. Ranger will crash

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

**Comment by robsss** [comment] 2022-05-16 02:04
Although I have the same problem as above. There is minor distinction which the OS and terminal are defferent.
Hope is helpful to debug.


#### Runtime Environment

- Operating system and version: Ubuntu 22.04 LTS
- Terminal emulator and version: tmux 3.2a
- Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Current Behavior

In this GitHub repo [my-linux-config](https://github.com/brpaz/my-linux-setup), when I trying open the file `alacritty.yml`, the terminal file system throw me this `ValueError`

#### Expected Behavior

Possiblly, the ranger provide me a preview of the content.

#### Context


#### Possible Solutions

#### Steps to reproduce
1. `git clone git@github.com:brpaz/my-linux-setup.git && cd my-linux-setup && ranger . `
2. switch to `alacritty.yml` file 

#### Traceback

```
❯ cd Projects/my-linux-setup
❯ ranger .
ranger version: ranger 1.9.3
Python version: 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
Locale: en_US.UTF-8
Current file: '/home/richard/Projects/my-linux-setup/alacritty.yml'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by Lowband21** [comment] 2022-05-17 01:02
I'm having the same issue, has basically made Ranger unusable for me.

Runtime Environment

    Operating system and version: Arch Linux
    Terminal emulator and version: alacritty 0.10.1
    Python version: Python 3.10.4
    Ranger version/commit: ranger 1.9.3
    Locale: en_US.UTF-8

Current Behavior

Ranger crashes when previewing markdown files with links in them.
Expected Behavior

Ranger should display a highlighted preview of markdown files.
Steps to reproduce

    Create a test.md file.
    Add a link to the MD file:

[a link](example.com)

    Open ranger, and navigate over the file.
    Ranger will crash

**Comment by Randomneo** [comment] 2022-06-05 17:15
Solution I could found on the internet. And it feels most appropriate.

Add to `.bashrc` or `.zshrc` or your shell rc
```
export TERM=xterm-256color
```

**Comment by rightaway** [comment] 2022-07-16 07:07
@toonn Can @nadapez's fix be merged so it doesn't crash when it has problems like these?

**Closed** 2022-07-22 08:34 UTC

**Comment by rightaway** [comment] 2022-07-26 06:27
@dav1ta Why did you close this as completed?

**Comment by dav1ta** [comment] 2022-07-27 17:22
> @dav1ta Why did you close this as completed?

Do not have same problem in newer versions.

**Comment by rightaway** [comment] 2022-08-02 10:06
@dav1ta Which version? It hasn't been fixed. Still breaking for me.

**Comment by Randomneo** [comment] 2022-08-05 08:59
@rightaway can't reproduce on 1.9.3

**Comment by JarrodBaker** [comment] 2022-08-05 09:56
I still have the same problem @Randomneo. For example, when I try and preview the following file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>example</artifactId>
    <version>0.9</version>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>commons-cli</groupId>
            <artifactId>commons-cli</artifactId>
            <version>1.5.0</version>
        </dependency>
    </dependencies>

</project>
```
Ranger crashes with the same error messages reported above. 

`ranger --version` shows:

```
ranger version: ranger 1.9.3
Python version: 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0]
Locale: en_GB.UTF-8
```

Running in tmux (version `tmux 3.2a`) on Ubuntu. 

Output of `uname -a`

```
uname -a
Linux xxx 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Randomneo** [comment] 2022-08-05 10:22
@JarrodBaker I created test.xml with content you provided and preview works just fine for me.
```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8
```

```
$ uname -a
Linux randomneo-pc 5.18.15-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 29 Jul 2022 22:52:39 +0000 x86_64 GNU/Linux
```

But probably this got solved by `TERM=tmux-256color`. Could you please show your? `echo $TERM`

As I pointed before this problem could be solved with tuning TERM. But now it works without config `xtrem-256color`
Also I don't know what `$TERM` I had when problem was there.

Some of my software versions:
```
tmux-3.3a-2
rxvt-unicode-9.30-1
```

**Comment by JarrodBaker** [comment] 2022-08-05 10:42
The output of `echo $TERM` was `xterm-256color`. Updating the value to `tmux-256color` solves the issue for me.

**Comment by idvorkin** [comment] 2022-12-24 15:12
I love ranger, super fast and helpful! 

Unfortunately, I'm getting the same crash. I see some workarounds by setting the correct TERM, but that's a high burden for users for which all apps work.  Is there a workaround for incorrect TERMs, by handling the exception gracefully? 

```
  File "/opt/homebrew/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/opt/homebrew/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

Ranger Version:
```
ranger version: ranger 1.9.3
Python version: 3.10.7 (main, Sep 14 2022, 22:38:23) [Clang 14.0.0 (clang-1400.0.29.102)]
Locale: en_US.UTF-8
```
OS Version:
```
Darwin idvorkin-mbp 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:13:46 PDT 2022; root:xnu-8020.240.7~1/RELEASE_ARM64_T8101 arm64
```

**Comment by EsGeh** [comment] 2023-04-11 14:45
Still getting this crash when selecting a Markdown (.md) file.

Ranger Version:

```
$ ranger --version
ranger version: ranger 1.9.3
Python version: 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201]
```

Linux Distribution:

Arch Linux

**Comment by sz-hankus** [comment] 2023-04-12 15:53
@EsGeh Did you install ranger from source (by cloning this repo), or from some repository using a package manager (presumably from AUR using pacman)?

**Comment by rightaway** [comment] 2023-04-20 21:27
@toonn Is a new release planned so we can get it it from package manager?

**Comment by toonn** [comment] 2023-04-24 11:35
@rightaway, yes but it'll take quite a while longer. I want to get the known bugs in milestone 1.9.4 addressed before cutting a release. In the meantime, some distros package the master branch, like `ranger-git` in the AUR. Or you can just clone the repository and run `make install`. Or even run Ranger from the repo without installing.

**Comment by rightaway** [comment] 2023-05-06 01:14
@toonn I'll do that but most people just use the version from a package manager but there is 150 issues left for milestone 1.9.4 so it won't be possible to get years of fixes and features for them.

**Comment by hiredgunhouse** [comment] 2024-05-10 08:22
That seems to be a problem on Ranger 1.9.3 and Pop_OS! 
Workaround from @nadapez (https://github.com/ranger/ranger/issues/2583#issuecomment-1097438886) works.

**Comment by Flinner** [comment] 2024-11-26 13:12
still crashes for me :(
when `TERM=xterm` it crashes, solved by `TERM=xterm-256color`

**Comment by vasekhodina** [comment] 2025-03-08 16:54
If someone is still experiencing this on 1.9.4. like I did, and wants to set TERM=xterm-256color.
Don't set TERM manually via .bashrc. You need to set
```
XTerm.termName: xterm-256color
```
OR
```
UXTerm.termName: xterm-256color
```
in your .Xresources. Then after relogging the TERM var should be set correctly.
If you set TERM manually it will lead to inconsisten behaviour where TERM will be set when running interactive shell, but not when ranger is executed via X.
