### ISSUE TITLE
Ranger crashes previewing text files with bat

### ISSUE THREAD

**Issue by tmzhuang** [ranger/ranger#2551] opened 2022-01-26 14:03 UTC
#### Runtime Environment
- Operating system and version: 
Linux jupiter 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux
- Terminal emulator and version: 
alacritty 0.10.0 (8a26dee0)
- Python version: 
Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]
- Ranger version/commit: 
ranger version: ranger 1.9.3
- Locale: 
en_US.UTF-8
#### Current Behavior
Ranger crashes with a python error.
#### Expected Behavior
Preview file with bat
#### Context
Using bat version:
bat 0.19.0 (59a8f58b)

#### Steps to reproduce
1. Start ranger
2. Select a text file

#### Traceback
```
Traceback (most recent call last):
  File "/home/tzhuang/proj/ranger/ranger/core/main.py", line 204, in main
    fm.loop()
  File "/home/tzhuang/proj/ranger/ranger/core/fm.py", line 416, in loop
    ui.redraw()
  File "/home/tzhuang/proj/ranger/ranger/gui/ui.py", line 343, in redraw
    self.draw()
  File "/home/tzhuang/proj/ranger/ranger/gui/ui.py", line 370, in draw
    DisplayableContainer.draw(self)
  File "/home/tzhuang/proj/ranger/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/home/tzhuang/proj/ranger/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/home/tzhuang/proj/ranger/ranger/gui/displayable.py", line 268, in draw
    displayable.draw()
  File "/home/tzhuang/proj/ranger/ranger/gui/widgets/browsercolumn.py", line 184, in draw
    self._draw_file()
  File "/home/tzhuang/proj/ranger/ranger/gui/widgets/browsercolumn.py", line 211, in _draw_file
    Pager.draw(self)
  File "/home/tzhuang/proj/ranger/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/home/tzhuang/proj/ranger/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/home/tzhuang/proj/ranger/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/home/tzhuang/proj/ranger/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

**Comment by tmzhuang** [comment] 2022-01-26 14:07
I am explicitly setting TERM=xterm which seemed to be causing the issue. Removing it fixed it for me.

**Comment by toonn** [comment] 2022-02-27 15:38
Closing this because it's already being tracked in #2524.

**Comment by toonn** [comment] 2022-11-18 10:03
Actually closing this as a duplicate of #2498.

**Closed by toonn** 2022-11-18 10:03 UTC
Labels: duplicate
