### ISSUE TITLE
Ranger column broken in Kitty terminal

### ISSUE THREAD

**Issue by s0344** [ranger/ranger#1692] opened 2019-09-12 17:39 UTC
#### Runtime Environment

- Operating system and version:  awesome with archlinux
- Terminal emulator and version: kitty 0.14.4
- Python version: Python 3.7.4
- Ranger version/commit: Ranger 1.9.2
- Locale: None

#### Current Behavior
On kitty when I run ranger it is like this.
![2019 09 12-13 35 33 screenshot](https://user-images.githubusercontent.com/44009744/64807054-6769a980-d562-11e9-992c-667542fb8d9a.png)

#### Expected Behavior
expected behavior should be like this in konsole
![2019 09 12-13 30 52 screenshot](https://user-images.githubusercontent.com/44009744/64807020-5456d980-d562-11e9-8349-7fbc15c8711d.png)

#### Context

It makes ranger hard to use in Kitty terminal

#### Possible Solutions
Have no idea. I have been googling and didn't find any solution.
The only way is to uninstall ly display manager.

#### Steps to reproduce
1. I installed ly display manager
2. reboot
3. Here I am

**Comment by kovidgoyal** [comment] 2019-09-15 03:50
The way to debug these kinds of issues in kitty is to run it with --dump-bytes and perform a minimal set of actions to produce the problem. Then open a bug report and attach the dump file. The by simply catting the dump file it becomes possible to recreate the issue and one can then use --dump-commands and --replay-commands to narrow down which commands are behaving unexpectedly.

**Comment by kovidgoyal** [comment] 2019-09-15 03:51
Although I would guess this issue is caused by setting TERM to something other than xterm-kitty

**Comment by s0344** [comment] 2019-09-16 01:14
I didn't find the problem. However, instead of using ly, I uninstalled it and install ly-git and it somehow fix it...

**Comment by toonn** [comment] 2019-09-16 10:39
👍 Closing as not our bug then.

**Closed by toonn** 2019-09-16 10:39 UTC
