### ISSUE TITLE
Ranger crashes after upgrade to 1.9.3-1

### ISSUE THREAD

**Issue by mushruptor** [ranger/ranger#1849] opened 2020-02-22 14:12 UTC
#### Runtime Environment

**Arch**: 5.5.5.arch1-1
**Ranger version**: ranger 1.9.3
**Python version**: 3.8.1
**Terminal**: xfce4-terminal 0.8.9.1 
**Locale**: en_GB.UTF-8

#### Traceback

> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 171, in main
>     fm.initialize()
>   File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 104, in initialize
>     set_image_displayer()
>   File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 103, in set_image_displayer
>     self.image_displayer = get_image_displayer(self.settings.preview_images_method)
>   File "/usr/lib/python3.8/site-packages/ranger/ext/img_display.py", line 99, in get_image_displayer
>     image_displayer_class = IMAGE_DISPLAYER_REGISTRY[registry_key]
>   File "/usr/lib/python3.8/site-packages/ranger/ext/img_display.py", line 79, in fallback_image_displayer
>     raise ImgDisplayUnsupportedException
> ranger.ext.img_display.ImgDisplayUnsupportedException

#### Context

After launching, ranger immidiately crashes with the above traceback.

Happened after upgrading from 1.9.2-2 to 1.9.3-1 
I installed the current git version as well and it gives the same behavior.

Reinstalling 1.9.2-2 and everything works as expected again.

**Comment by toonn** [comment] 2020-02-22 19:31
Closing as a duplicate of #1846.
Something about python 3.8 seems to mess with how things work.

**Closed by toonn** 2020-02-22 19:31 UTC
