### ISSUE TITLE
'open_with%space' doesn't add space character at the end

### ISSUE THREAD

**Issue by JadowityHerbatnik** [ranger/ranger#1857] opened 2020-02-25 20:10 UTC
#### Runtime Environment

- Operating system and version:  Arch Linux
- Terminal emulator and version:  alacritty 0.4.1
- Python version: 3.8.1
- Ranger version/commit:  1.9.3
- Locale: en_US.UTF-8

#### Current Behavior
After updating ranger do 1.9.3 there's no space character added after `console open_with%space`. Weirdly enough it works with all other commands (e.g. `console shell%space` or `console find%space`), but whenever I use my keybinding for  `console open_with%space` (I use the default `r` key), I have to type space before any input.
Here's my exact binding: `map r  chain draw_possible_programs; console open_with%space`

#### Expected Behavior
`console open_with%space` should work just like any other command and add a trailing space character

**Comment by toonn** [comment] 2020-02-26 11:10
Hmm, I can't reproduce this. Does it happen if you run ranger with a different version of python?

We did change the behavior of macro resolving for chain, it should ignore them because they are resolved again for each of the commands. If we don't do this we end up resolving macros twice which is a problem with escapes, `%%s` for example.

**Comment by JadowityHerbatnik** [comment] 2020-02-26 13:09
Just installed python 3.7 and it's the same (I ran `/usr/bin/ranger` with the shebang changed to python 3.7).
As I said, it works in ranger 1.9.2 with python 3.8, so I don't think it's a python issue. Which file is responsible for resolving macros?

**Comment by JorgeDLG** [comment] 2020-02-27 10:40
Same problem for me, %space doesn't add a space when using r keybind. I have to delete and type space character.

**Comment by marcbelmont** [comment] 2020-02-27 13:17
On version 1.9.2, **r keybinding** used to give me the prompt `open_with ` 

I am now using ranger-fm 1.9.3, Python 3.6.9 and the prompt changed to `open_with%space`

For some reason my `rc.conf` contained:
`map r  chain draw_possible_programs; console open_with%%space`

Changing it to the following fixed the issue.
`map r  chain draw_possible_programs; console open_with%space`

**Comment by toonn** [comment] 2020-02-27 13:46
I suspect that's the issue @JadowityHerbatnik and @JorgeDLG are running into too? Means the config is old, maybe rerun `ranger --copy-config=rc`. (Or get rid of it entirely if you don't customize it anyway.)

**Comment by JadowityHerbatnik** [comment] 2020-02-27 14:14
> For some reason my rc.conf contained:
> map r chain draw_possible_programs; console open_with%%space

> Changing it to the following fixed the issue.
> map r chain draw_possible_programs; console open_with%space

Interesting, for me it was the other way round - changing `%space` to `%%space` in my `$HOME/.config/ranger/rc.conf` solved the issue. Which is bizzare, because I didn't override the default `r` key mapping and both my `/usr/lib/python3.8/site-packages/ranger/config/rc.conf` and `/usr/share/doc/ranger/config/rc.conf` contained only "single percent sign" mapping.

Why did this behavior change? And apparently affected only some users?

**Comment by toonn** [comment] 2020-02-27 15:57
@JadowityHerbatnik, `%%space` shouldn't work anymore, are you sure you're not using 1.9.2?

**Comment by JadowityHerbatnik** [comment] 2020-02-27 16:55
Unless both `ranger --version` and `pacman -Qi ranger` are wrong, I'm pretty sure it's 1.9.3.

**Comment by toonn** [comment] 2020-02-28 10:29
@JadowityHerbatnik, so if you run `ranger --clean` `r` doesn't work?
@marcbelmont, same thing for you, except it *should* work.

**Comment by JadowityHerbatnik** [comment] 2020-02-28 11:07
> @JadowityHerbatnik, so if you run ranger --clean r doesn't work?

@toonn It works as intended!  That means there must be something in my configuration that breaks it, which would be weird, because up until yesterday I haven't changed the dafult `r` key binding. 
Anyway, [here](https://github.com/JadowityHerbatnik/dotfiles/tree/archi3/.config/ranger) are my config files if anybody cares. 

One thing that is different though is the cursor shape when invoking any command - not just `open_with`. In  'clean mode' the cursor is just a vertical line and when using my configuration it's a filled, one character wide rectangle - not that it matters, just something I noticed.

**Comment by JadowityHerbatnik** [comment] 2020-02-28 11:15
Okay, I figured it out. I didn't have `resolve_macros = False` in my `commands.py` file.

**Comment by toonn** [comment] 2020-02-28 11:34
Oh, right, good find! Completely forgot to ask whether you had a `commands.py`.

PSA: Ranger docs used to recommend to run `ranger --copy-config=all`. DO NOT do this anymore, only have the config files around that you customize to avoid as many of these problems as possible.

**Comment by JadowityHerbatnik** [comment] 2020-02-28 11:56
> PSA: Ranger docs used to recommend to run ranger --copy-config=all. DO NOT do this anymore, only have the config files around that you customize to avoid as many of these problems as possible.

Well, I've made some changes to all of them and as far as I understand, it only makes sense for `rc.conf` and `commands.py` to not copy the entire file and keep only custom changes in the user config directory. For `rifle.conf` and `scope.sh` we need to copy the entire file, because the order of lines is relevant and (I guess) when ranger loads two files, the one that is loaded later (user config) is "appended" at the end making any user changes be of least priority.

**Comment by toonn** [comment] 2020-02-28 15:09
@JadowityHerbatnik, that was a PSA, i.e., not directed at you.

Rifle only ever loads a single file and the path to scope is configured in `rc.conf` so there's no appending going on.

For `rc.conf` things loaded later, i.e., the user's config, override the defaults, same thing for `commands.py`.

**Closed** 2020-05-19 16:54 UTC
