### ISSUE TITLE
Mediainfo CPU hogging

### ISSUE THREAD

**Issue by Q3CPMA** [ranger/ranger#813] opened 2017-02-20 17:17 UTC
When passing over multiples media files, the mediainfo preview is launched for every passed file, hogging 100% of my CPU. It sounds reasonable to me to abort the preview process when the file isn't the one under the cursor anymore.

I kinda solved it by using ffprobe instead (less dependencies and a lot faster)

Using 1.8.1 on Gentoo

**Comment by nfnty** [comment] 2017-02-21 03:11
Duplicate of #202.

**Closed by nfnty** 2017-02-21 03:11 UTC
