### ISSUE TITLE
 image preview feature not work in OSX

### ISSUE THREAD

**Issue by tanrax** [ranger/ranger#864] opened 2017-05-11 08:40 UTC
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: macOS Sierra 10.12.4
- Terminal emulator and version: ITerm2 3.0.14
- Python version: Python 2.7.10 
- Ranger version/commit: ranger-stable 1.8.1

Python 2.7.10 (default, Feb  6 2017, 23:53:20)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
- Locale: 

#### EXPECTED BEHAVIOR

Preview images

#### CURRENT BEHAVIOR

No pictures are shown

#### STEPS TO REPRODUCE

1. I added my rc.conf
2. 

```
set preview_images true
set preview_images_method iterm2

```
3. Open ranger

#### TRACEBACK

```

```

**Comment by nfnty** [comment] 2017-05-14 15:49
Have you tested running on `master`?

**Comment by tanrax** [comment] 2017-05-14 15:58
Yes. Same results

**Comment by tanrax** [comment] 2017-05-14 16:00
![screen shot 2017-05-14 at 18 00 06](https://cloud.githubusercontent.com/assets/4553672/26035578/2ef7ff84-38cf-11e7-8d08-4033c9b00951.jpg)

**Comment by mlopes** [comment] 2017-05-20 13:58
I think I may have some extra information that might help here. I thought it didn't work for me but turns out it does... but only for images smaller than around 42k. Anything  bigger than that doesn't get a preview.
See the attached screenshots:
![image](https://cloud.githubusercontent.com/assets/654/26276309/bae6c2f4-3d6c-11e7-9c5c-c31d9f03ee4c.png)

Now an image bigger than 42k:

![image](https://cloud.githubusercontent.com/assets/654/26276313/ccce73b8-3d6c-11e7-99cb-279195b40f06.png)

I was able to reproduce this consistently.

**Comment by tanrax** [comment] 2017-05-22 14:50
I can not see it.
![screen shot 2017-05-22 at 16 47 27](https://cloud.githubusercontent.com/assets/4553672/26314552/a693c538-3f0e-11e7-8b47-50a8c6958218.jpg)
![screen shot 2017-05-22 at 16 48 19](https://cloud.githubusercontent.com/assets/4553672/26314553/a7d1448e-3f0e-11e7-9cd0-c14505333ebd.jpg)

How can I give you more information? Thank you

**Comment by Wes974** [comment] 2017-07-16 19:48
I found a way to make it work.
Copy the folder `~/.config/ranger/` somewhere on your computer (your Desktop for example) then remove everything in `~/.config/ranger/`. 

Open iTerm and run this command :

```
ranger --copy-config=all
```

Once this is done, open your `~/.config/ranger/rc.conf` file to edit those line

```
set preview_images true
set preview_images_method iterm2
```
Let me know if it worked for you.

**Comment by tanrax** [comment] 2017-07-16 19:59
It does not work for me. What version of python do you use?

**Comment by Wes974** [comment] 2017-07-16 20:00
I use python 2.7.13

**Comment by tanrax** [comment] 2017-07-16 20:07
I followed your steps, with both the brew version and the master version with no results. :(

**Comment by Wes974** [comment] 2017-07-16 20:12
All right we can try another thing, in your `rc.conf`, find this line :

    set draw_borders false

Set it to `true` and relaunch ranger. See if it changes something.

**Comment by tanrax** [comment] 2017-07-16 20:17
![screen shot 2017-07-16 at 22 16 37](https://user-images.githubusercontent.com/4553672/28250993-7d234ae8-6a74-11e7-95b9-13322b4efd76.jpg)
![screen shot 2017-07-16 at 22 16 34](https://user-images.githubusercontent.com/4553672/28250994-7d23c45a-6a74-11e7-9048-38ae1d0d14e4.jpg)
![screen shot 2017-07-16 at 22 16 28](https://user-images.githubusercontent.com/4553672/28250995-7d241eb4-6a74-11e7-948f-920ec8addbb5.jpg)
![screen shot 2017-07-16 at 22 16 22](https://user-images.githubusercontent.com/4553672/28250996-7d27780c-6a74-11e7-8c29-47b04176aec0.jpg)

**Comment by Wes974** [comment] 2017-07-16 20:23
Hey are you running ranger inside of tmux by any chance ?

**Comment by tanrax** [comment] 2017-07-17 05:39
I try everything in and out of Tmux.

**Comment by Wes974** [comment] 2017-07-17 12:11
Well then I don't know what to do, sorry

**Comment by toonn** [comment] 2018-03-13 10:59
@looneym tmux is a lot more limited than regular terminals in what it can do I don't think it supports any of the previewing methods.
@tanrax Do you still have this issue?

**Comment by tanrax** [comment] 2018-03-13 16:39
@toonn I didn't get it to work... the problem persists.

**Comment by toonn** [comment] 2018-03-13 17:29
Could you remove your `scope.sh` and comment out the line `set preview_script ~/.config/ranger` in `rc.conf`? Don't try in tmux it won't work.

**Comment by tanrax** [comment] 2018-03-13 17:45
ohh!
![screen shot 2018-03-13 at 18 44 42](https://user-images.githubusercontent.com/4553672/37359746-b0eb7288-26ee-11e8-97b1-2a205e92a39e.jpg)

**Comment by toonn** [comment] 2018-03-14 13:09
Did you comment out or remove the set preview_script line? And try running ranger with the `--debug` flag, might give us some more info.

**Comment by BenBergman** [comment] 2018-04-14 16:59
I have image previews working for me in iterm2 both in and out of tmux, but if I am inside tmux I can only preview images that are under ~85k. Is there any setting I can add to make it work better in tmux?

**Comment by toonn** [comment] 2018-04-14 22:16
Not that I know of sadly.

**Comment by jsatk** [comment] 2018-12-21 07:14
I'm in the exact same boat as @tanrax. I just tried everything listed in here. Nothing works. I just get prompted to "open with".  @wes974's comment [here][1] installed a bunch of new stuff I didn't have in ~/.config/ranger, but it didn't fix my problem. 

[1]: https://github.com/ranger/ranger/issues/864#issuecomment-315632418

**Comment by jsatk** [comment] 2018-12-28 05:32
@BenBergman any chance you could share what your config looks like? I'm in tmux + iTerm as well.

**Comment by jsatk** [comment] 2018-12-28 05:39
@toonn This is the entirety of my `~/.config/ranger.rc.conf`.

```conf
# https://github.com/ranger/ranger/wiki/Image-Previews#with-iterm2
set preview_images true
set preview_images_method iterm2
```

And my `~/.config/ranger/rifle.conf` is the exact default one with this single line added.

```conf
mime ^image,                      flag f = open -- "$@" # Open images in Preview.app on macOS.
```

**Comment by jsatk** [comment] 2018-12-28 06:01
Update — the above does work in iTerm 2. It just doesn't work in tmux + iTerm 2. As said a few times in this issue, it's anticipated that image preview won't work in tmux. If anyone knows how to get it to work I'm all ears, but as far as I'm concerned this issue is resolved for me since it is working in iTerm 2 and has been explicitly stated that it won't work in tmux.

**Comment by BenBergman** [comment] 2019-01-14 15:33
@jsatk Here is my `~/.config/ranger/rc.conf`: https://gist.github.com/BenBergman/f95a558c3f73c90222639dc4f215f448

That file was either auto generated or I stole it from somewhere as I don't recall ever editing it before, at least not all of those lines.

I also tossed in my `.tmux.conf` in case there is anything helpful in there. That one is more handcrafted by me.

In case it is relevant, I also use `zsh` instead of `bash`.

**Comment by toonn** [comment] 2019-12-18 21:28
I'm closing this in the hope that #1601 fixed it.

**Closed by toonn** 2019-12-18 21:28 UTC
Labels: bug, image-preview

**Comment by hawkinchina** [comment] 2020-01-09 02:01
I meet the same problem. it works outside of tmux,  but inside tmux, it cannot work. this issue has already fixed, or not ?

**Comment by toonn** [comment] 2020-01-09 15:09
Yes, but I doubt you're running 1.9.3 already?

**Comment by hawkinchina** [comment] 2020-01-09 15:47
my ranger‘s version： 1.9.3

➜  /Users/jack >ranger --version
ranger version: ranger 1.9.3
Python version: 3.7.5 (default, Nov  1 2019, 02:16:38) [Clang 10.0.0 (clang-1000.11.45.5)]
Locale: zh_CN.UTF-8

**Comment by toonn** [comment] 2020-01-10 17:18
Then you're probably trying to preview "large" images. Tmux prevents images larger than a couple kB from being shown. Nothing we can do about that.

**Comment by ayushkumarshah** [comment] 2020-05-23 12:34
> I found a way to make it work.
> Copy the folder `~/.config/ranger/` somewhere on your computer (your Desktop for example) then remove everything in `~/.config/ranger/`.
> 
> Open iTerm and run this command :
> 
> ```
> ranger --copy-config=all
> ```
> 
> Once this is done, open your `~/.config/ranger/rc.conf` file to edit those line
> 
> ```
> set preview_images true
> set preview_images_method iterm2
> ```
> 
> Let me know if it worked for you.

Thank @Wes974. It works perfectly. However, it asked me permission to allow download of files by term. Does this method download images somewhere?

**Comment by toonn** [comment] 2020-05-23 19:23
Maybe iTerm2 doesn't include the imgcat functionality necessary for the previews but is able to download it automatically? No idea though, never heard of this.
