### ISSUE TITLE
Firefox - Open Containing Folder with Ranger/URxvt.

### ISSUE THREAD

**Issue by relaxeaza** [ranger/ranger#1164] opened 2018-05-06 03:00 UTC
#### Runtime Environment
- Operating system and version: Arch Linux 4.16.6-1
- Terminal emulator and version: rxvt-unicode (urxvt) v9.22
- Python version: 3.6.5 (default, Apr 14 2018, 13:17:30) [GCC 7.3.1 20180406]
- Ranger version/commit: ranger-master 1.9.1
- Locale: en_US.UTF-8
- Firefox version: Mozilla Firefox 59.0.2
#### Current Behavior
When urxvt is the default terminal, nothing happens when `/usr/bin/ranger` is selected to open the folder location of downloaded files on Firefox.
With xterm installed, the folder opens normally using it.

Edit: Same behavior on Manjaro Linux.

#### Possible Solutions
Using a shell script `urxvt -e ranger "$@"` works.

**Comment by D-Vaillant** [comment] 2018-06-13 23:57
- What's the name of the download location?
- Does it still not work if you change the Firefox download folder location?

**Comment by mafrazz** [comment] 2018-06-14 02:47
`$HOME/Downloads/`
Same behavior no matter the folder the file is located. It's probably what @toonn said, a Firefox issue.

**Comment by D-Vaillant** [comment] 2018-06-14 07:38
Yeah, I'm assuming it has something to do with the way that Firefox is passing the arguments to the command and the difference in the way that urxvt and xterm respond to that. Ranger is a victim here, not the culprit.

**Comment by toonn** [comment] 2018-06-14 12:06
How about adding the following lines to `rifle.conf` and selecting rifle instead of ranger to open the downloads?

'''
directory, terminal = ranger -- "$@"
directory, flag t = ranger -- "$@"
'''

Note: flag t isn't great yet, falls back to xterm almost always but it'll be better in the next release.

**Comment by mafrazz** [comment] 2018-06-14 18:07
Nothing happens.
Trying directly on terminal:
```
$ rifle ~/Downloads
Unknown file type: inode/directory
```

```
$ rifle -l ~/Downloads
0:::ask
1:editor::${VISUAL:-$EDITOR} -- "$@"
2:pager::"$PAGER" -- "$@"
3:::ranger -- "$@"
4::t:ranger -- "$@"
```

**Comment by toonn** [comment] 2018-06-14 19:08
Ah, you probably added these lines to the very bottom of `rifle.conf`. Try adding them somewhere before the `Misc` section.

**Comment by mafrazz** [comment] 2018-06-14 20:55
Worked via terminal, but still nothing on Firefox.
May I close the issue?

**Comment by toonn** [comment] 2018-06-17 10:06
If the issue is satisfactorily resolved for you you can close it of course. Kinda curious why it doesn't work with firefox though.

**Comment by b1scu1t** [comment] 2018-07-15 18:54
I've got it to work by setting the default file manager with xdg-mime to ranger using the 'ranger.desktop' file. 
Then Firefox would open directories with 'xdg-open', which calls ranger.

**Comment by doronbehar** [comment] 2019-08-08 07:27
Hey, I think this can be closed. the same question was asked [on superuser.com](https://superuser.com/questions/1270462/how-to-make-firefox-open-cli-app-in-specified-terminal) and I've posted an [answer](https://superuser.com/a/1469035/430539) explaining the situation.

**Comment by toonn** [comment] 2019-08-08 14:22
@doronbehar, could you reproduce the answer here in common SE fashion?

**Comment by doronbehar** [comment] 2019-08-09 18:49
Sure, I'll quote my original answer from there, just for reference:

> Unfortunately, Firefox uses Gio which check for the existence several specific terminals in `$PATH`. See this:
> 
> https://gitlab.gnome.org/GNOME/glib/blob/2.21.6/gio/gdesktopappinfo.c#L773
> 
> As you can read, `rxvt-unicode-256color` and `$TERMINAL` are not checked. Therefor, IMO the best workaround for that should be linking your desired terminal's executable to `color-xterm` or perhaps better, `rxvt` in your case since it is checked (but `rxvt-unicode-256color` isn't).
> 
> Try the following command assuming `~/.bin/` is in your `$PATH`:
> 
> ```
> ln -s $(which rxvt-unicode-256color) ~/.bin/rxvt
> ```
> 
> Credit: https://bbs.archlinux.org/viewtopic.php?pid=1750642#p1750642

Yea I know, the terminals checked are hard-coded and it's horrible. Funny no one has proposed a solution for that..

**Comment by toonn** [comment] 2019-08-09 18:53
There's not really good solutions to the problem I'm afraid. Debian might have sensible-terminal or something and XDG probably has something but those aren't givens.
Closing because we have an answer. Discussion can still go on.

**Closed by toonn** 2019-08-09 18:53 UTC
Labels: not-our-bug

**Comment by rod-stuchi** [comment] 2019-10-30 23:21
I made it work by changing some files:

.local/share/applications/ranger.desktop
```
...
Terminal=false
Exec=konsole -e ranger %u
...
```

.config/mimeapps.list
```
...
[Default Applications]
inode/directory=ranger.desktop
...
```

**Comment by toonn** [comment] 2019-10-31 07:44
This is basically all we can do for now. I'm still confident we can make it work better using `rifle` though. But first we have to sort out the `flag t` business.

**Comment by c02y** [comment] 2022-04-22 05:20
> I made it work by changing some files:
> 
> .local/share/applications/ranger.desktop
> 
> ```
> ...
> Terminal=false
> Exec=konsole -e ranger %u
> ...
> ```
> 
> .config/mimeapps.list
> 
> ```
> ...
> [Default Applications]
> inode/directory=ranger.desktop
> ...
> ```
`Terminal=false` is the key point here, or else it won't work.
