### ISSUE TITLE
`Home` or `End` keys make ranger crash

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#780] opened 2017-01-26 03:49 UTC
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Fedora 25 64-bit
- Terminal emulator and version: Konsole v16.08.3, fish-shell v2.3.1, tmux v2.2
- Python version: 3.5.2
- Ranger version/commit: 1.8.1 commit 2d8affddf55ab352afce58b846da45b90d715b9b 

#### EXPECTED BEHAVIOR

Won't crash.

#### CURRENT BEHAVIOR

When I type `Home` or `End` key in the ranger (even a new ranger session`), ranger will crash.

#### STEPS TO REPRODUCE

1. Type `Home` or `End` key in the ranger (even a new ranger session`)

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 3.5.2
Locale: en_US.UTF-8
Current file: /home/chz/Public/ranger/build
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/ranger/core/main.py", line 166, in main
    fm.loop()
  File "/usr/lib/python3.5/site-packages/ranger/core/fm.py", line 371, in loop
    ui.draw_images()
  File "/usr/lib/python3.5/site-packages/ranger/gui/ui.py", line 370, in draw_images
    if self.browser.pager.visible:
AttributeError: 'NoneType' object has no attribute 'visible'
```

**Comment by nfnty** [comment] 2017-01-26 04:21
Can't reproduce.

Test the following:
- Run with `ranger --clean`
- Run without `tmux`
- Run in other terminal emulators

**Comment by c02y** [comment] 2017-01-26 04:59
After testing, I believe it is the problem of tmux, but how can I solve this?

**Comment by nfnty** [comment] 2017-01-26 05:17
Should be fixed now. Test `master`.

**Closed** 2017-01-26 05:16 UTC

**Comment by c02y** [comment] 2017-01-26 08:03
Got no access to my computer in the next several days, I'll test it after that right away.

**Comment by c02y** [comment] 2017-01-30 13:36
Here is the result of my test:

When I type `Home` or `End` in the list of the current directory, I think they should move point to the top/bottom of the list. But in the latest version of github master, both `Home` and `End` just toggle between the view of one column and three columns.

**Comment by nfnty** [comment] 2017-01-30 13:45
Try setting `setw -g xterm-keys on` in your tmux config.

**Comment by c02y** [comment] 2017-01-30 13:52
The same result, whether `--clean` or not.

**Comment by nfnty** [comment] 2017-01-30 14:55
And you're sure that the setting applied? You need to restart the tmux server after adding new settings to the config. Try setting it from the command line while in a session.

Also try adding:
```
set -s default-terminal "screen-256color"
set -s terminal-overrides "*256col*:colors=256,xterm*:XT,xterm-termite:Tc"
```

What tmux version are you using?

**Comment by c02y** [comment] 2017-01-30 17:01
The only thing I should do is to change `default-terminal` from "xterm-256color" to "screen-256color", I use "xterm-256color" all the time and nothing goes wrong, after changing it, `Home` and `End` works fine now. Thank you.

Just being curious, is "screen-256color" better than "xterm-256color"?

**Comment by nfnty** [comment] 2017-01-30 21:05
Read the man page `tmux(1)`:
```
 default-terminal terminal
         Set the default terminal for new windows created in this session - the default value of the TERM environment variable.  For tmux to work correctly,
         this must be set to ‘screen’, ‘tmux’ or a derivative of them.
```

**Comment by kankaristo** [comment] 2020-12-04 20:17
Sorry to resurrect an old issue, but this was the first Google result for "tmux ranger home key".

None of the above settings helped me, `Home` and `End` were still toggling between one-column and three-column views.

But that was only happening with tmux+zsh. Just tmux (with bash) worked fine, and just zsh (without tmux) worked fine.

In the end, the solution was basically the same. I was setting `export TERM="xterm-256color"` in my `~/.zshrc`. It's the default, I'm not sure why I was setting it "manually".

Setting it in `~/.zshrc` meant that tmux's setting of `screen-256-color` was effectively ignored. Removing that line from `~/.zshrc` fixed everything.
