### ISSUE TITLE
rifle and window title/update_tmux_title

### ISSUE THREAD

**Issue by rafi** [ranger/ranger#154] opened 2014-09-05 13:13 UTC
1. If `update_title` enabled, could the rifle file executor update the window title with the program it executed?
2. If `update_tmux_title` enabled, could the rifle update tmux's pane title in the same fashion?

The title can still have ranger's title if you'd like, e.g. `ranger: ~ vim` or it can completely overshadow it, e.g. `vim`.

My use-case is triggers I wrote into the window manager's keybindings that are program-aware by the title.

Thanks for this great piece of software :)

**Comment by randynobx** [comment] 2015-03-09 19:14
Number 2 is probably very doable. I'm working on a patch that would update the tmux window title back to the previous application (usually the shell) when ranger is exiting; but updating for programs that ranger is launching should be an even easier task.

I will work on incorporating this into my tmux patch as well.

**Comment by rafi** [comment] 2015-03-13 09:51
@randynobx sounds great, would love to see your patch when it's done.

**Comment by nfnty** [comment] 2017-01-25 19:54
Duplicate of #228.

**Closed by nfnty** 2017-01-25 19:54 UTC
