### ISSUE TITLE
bulkrename failure with mvim

### ISSUE THREAD

**Issue by a7hybnj2** [ranger/ranger#1477] opened 2019-02-15 04:23 UTC
#### Runtime Environment

- Operating system and version: macOS Mojave 10.14.3
- Terminal emulator and version: macOS Terminal 2.9.1
- Python version: Python 2.7.15
- Ranger version/commit: 1.9.2

I am able to set $EDITOR to vim and use ranger - bulkrename but, when I set $EDITOR to mvim and try to use bulkrename I get an mvim window that is empty.

I "mv ~/.vimrc ~/.vimrc_save" to disable all my vim plugins and mvim still wasn't working.

Can anyone confirm if ranger bulkrename works with mvim and what I should try next to fix it.

**Comment by toonn** [comment] 2019-02-15 09:29
What is mvim? Can't really find anything. Unless you mean MacVim? You can't use a GUI editor with `bulkrename` or any editor that forks for that matter.

`bulkrename` keeps track of the process it spawns, waiting until it dies and then reads the file produced. If you use a forking process, like a GUI editor, the process spawned dies immediately after forking which means `bulkrename` reads an unchanged file and promptly removes it I suppose. 

We do it this way because watching the file for a change isn't reliable, your editor might autosave a version of the file that leads to data loss.

**Comment by a7hybnj2** [comment] 2019-02-15 17:01
@toonn Makes perfect sense. Now that I think about it when I was using ranger in the past it was with 'vim' and not 'mvim'(macvim). I wonder what I changed to make bulkrename open in mvim over vim. Does it just use the $EDITOR var or is there another way to set the ranger editor?

Thanks for the clarification.

**Comment by toonn** [comment] 2019-02-15 20:31
Well, `VISUAL` would take precedence over `EDITOR` in ranger but it would in most programs. It might be possible to set it in `rifle.conf` though. Replace `${VISUAL:-${EDITOR}}` with `vim` to try it out. That's not ideal of course, since that'd mean any file you open in ranger opens with vim rather than mvim. However, *if* setting it in `rifle.conf` *doesn't* work, there's a way: Change the bit in `rifle.conf` to mvim and start ranger with `env VISUAL=vim ranger`, then opening files would use the rifle rule and `bulkrename`'d stick to `VISUAL`.

Nope, just checked it, rifle takes precedence : /

**Comment by a7hybnj2** [comment] 2019-02-15 20:39
@toonn Thanks for the follow up.

I don't have a rifle.conf in ~/.config/ranger/rifle.conf(where I think it should be) or ranger/config/rifle.conf(where the man page lists)

I would be fine with everything I open using ranger using vim but everything outside of ranger sticking with mvim(macvim).

**Comment by toonn** [comment] 2019-02-16 12:47
Maybe you set `EDITOR` recently?

I'm closing this because it's a feature not a bug, unfortunately. This doesn't mean discussion can't continue.

**Closed by toonn** 2019-02-16 12:47 UTC

**Comment by a7hybnj2** [comment] 2019-02-16 14:13
@toonn Should I just copy over [conf](https://github.com/ranger/ranger/blob/master/ranger/config/rifle.conf) or is there a way to populate it? `ranger --make-conf` or something?

if rifle takes precedence for bulkrename then that would solve my problem, right? Set rifle to use vim and keep $EDITOR = mvim.

EDITOR has been set since I installed macvim which predated installing ranger...

**Comment by toonn** [comment] 2019-02-16 14:54
Curious. Maybe mvim changed to a forking model or something? It'd be cool if you could bisect this so we can find out if we actually *did* lose functionality.

You can run `ranger --copy-config=rifle` to get a populated `rifle.conf`.

**Comment by a7hybnj2** [comment] 2019-02-16 21:52
I tried
```
# original
#label editor, !mime ^text, !ext xml|json|csv|tex|py|pl|rb|js|sh|php  = ${VISUAL:-$EDITOR} -- "$@"
# my edit 190216
label editor, !mime ^text, !ext xml|json|csv|tex|py|pl|rb|js|sh|php  = ask
```
and it didn't work.

I then tried
```
# I have to use .vimvimrc because my .vimrc is used by macvim and is incompatible with cli vim
alias ranger='env VISUAL="vim -u ~/.vimvimrc" ranger'
```
and it worked but I kept getting this error while `:bulkrename`ing
```
"/var/folders/00/5c9vglkx6vs6dg0mb9rdyhj00000gn/T/tmpgn1MXI" [Incomplete last line] 4 lines,
 115 characters
Press ENTER or type command to continue
```

I am thinking this is close enough, for now, because once I hit enter it appears to work correctly. Just an odd error.

**Comment by toonn** [comment] 2019-02-17 16:26
Sounds like something might be misconfigured for your vim I've never seen that problem myself.

Did you try `vim -- "$@"` rather than `ask`? I'm not sure `:bulkrename` works with `ask`.

**Comment by a7hybnj2** [comment] 2019-02-18 01:53
@toonn Thanks! I did try `vim -- "$@"` so I don't know why that wasn't working. But, with that alias startup it works just fine.

The `[Incomplete last line]` only shows up 1 out of 25 times I use bulkrename. I haven't found any consistency in file contents that would explain it. And I have had it happen with default vim settings. `¯\_(ツ)_/¯`

I consider this solution good enough and I appreciate your time. Thanks again.

**Comment by cpchan** [comment] 2019-08-17 06:05
I tried out :bulkrename for the first time today and have the same problem, since I am using "--no-wait" as an argument for emacsclient- I prefer this so that I don't block Ranger. Maybe Ranger should have another "editor variable" that we can set to a no fork version for commands that needs it?

**Comment by toonn** [comment] 2019-08-17 12:01
Hmm, I *think* rifle uses `label EDITOR` to find the editor for bulkrename? So set that to a non-forking emacs then add a rule higher up in `rifle.conf` that matches `mime ^text` and uses a forking emacs.
