### ISSUE TITLE
Ranger as a default folder explorer

### ISSUE THREAD

**Issue by oshliaer** [ranger/ranger#1184] opened 2018-05-25 19:47 UTC
#### Runtime Environment

- Operating system and version: 
```
$ uname -a
Linux old 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial

```
- Terminal emulator and version: 
```
$ x-terminal-emulator -h
rxvt-unicode (urxvt) v9.21 - released: 2014-12-31
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,pixbuf,XIM,frills,selectionscrolling,wheel,slipwheel,smart-resize,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
```
- Python version: `Python 2.7.12`
- Ranger version/commit: 
```
$ranger --version 
ranger-stable 1.7.1

Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609]
```
- Locale: `en_US`
- DE
```
$ i3 -v
i3 version 4.11 (2015-09-30, branch "4.11") © 2009 Michael Stapelberg and contributors
```

#### Current Behavior
`$ xdg-open .` doesn't open the terminal with `ranger`
It returns
```
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at 
                                            update#setState idle
```
#### Expected Behavior
`$ xdg-open .` should open the terminal with ranger
#### Context

I've created the file in `/home/user/.local/share/applications/ranger.desktop` with content https://github.com/ranger/ranger/blob/master/doc/ranger.desktop and register that
```
$ xdg-mime query default inode/directory                                                               
/home/user/.local/share/applications/ranger.desktop
```
#### Possible Solutions
It seems I have an error in my Ubuntu.

#### Steps to reproduce
1. Create the ranger.desktop file if it doesn't exist
2. Register it `$ xdg-mime default ~/.local/share/applications/ranger.desktop  inode/directory`
3. Call `$ xdg-open .` 

#### Traceback

The ranger works fine. There is no a traceback

**Comment by toonn** [comment] 2018-05-26 14:01
I'm not sure where the problem is. Neither that regex nor `update#setState` appear anywhere in the codebase.

**Comment by oshliaer** [comment] 2018-05-28 13:58
@toonn , it seems it's not a Ranger problem. Should I close this issue here?

**Comment by toonn** [comment] 2018-05-28 14:18
Let's close it yeah. It'd be great if you posted your solution when you figure it out though, so people googling find solutions not just problems : )
Feel free to reopen if it turns out to be a ranger issue after all.

**Closed by toonn** 2018-05-28 14:18 UTC

**Comment by oshliaer** [comment] 2018-08-10 14:52
Ok. At now I move to Ubuntu 18 and I can't reproduce this issue on another version.

**Comment by oshliaer** [comment] 2018-08-10 15:54
And I solved this.

## Reasons

The next error is caused from MS Code.
```bash
Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/%{ <-- HERE (.*?)}/ at 
                                            update#setState idle
```
Just reinstall it.

## Solution

If you want `xdg-open .` to open the ranger in a separate window you can add small changes.

After all the next steps are suitable for general configuration

1. Set the default FM

```bash
$ xdg-mime default ranger.desktop inode/directory  
``` 

2. Override personal user settings

```bash
$ cp /usr/share/applications/ranger.desktop /home/user/.local/share/applications
```

3. Edit  `/home/user/.local/share/applications/ranger.desktop`. My example

```cofig
Exec=x-terminal-emulator -e ranger
```

4. For the configure `x-terminal-emulator `

```bash
$ sudo update-alternatives --config x-terminal-emulator  
```

I'm sure that is the right way for Ubuntu without any DE or WM except i3 WM.

**Comment by toonn** [comment] 2018-08-10 18:18
👍 Thank you for reporting back!
