### ISSUE TITLE
Ranger crashes with the code ValueError: Color number is greater than COLORS-1 (7).

### ISSUE THREAD

**Issue by pchest** [ranger/ranger#2721] opened 2022-10-20 21:38 UTC
#### Runtime Environment

- Operating system and version: Pop!_OS 22.04.1
- Terminal emulator and version: Gnome Terminal 3.44.0
- Python version: 3.10.6
- Ranger version/commit: 1.9.3
- Locale: USA

#### Current Behavior
Ranger unexpectedly crashes, giving the following error:
> ValueError: Color number is greater than COLORS-1 (7).
#### Expected Behavior
Ranger should not randomly crash
#### Context

It has happened once so far.
#### Steps to reproduce
1. Open ranger
2. Navigate to a directory
3. Ranger crashes

#### Traceback

```
"ValueError: Color number is greater than COLORS-1 (7)."
```

**Comment by toonn** [comment] 2022-11-18 10:09
Closing as duplicate of #2498.

**Closed by toonn** 2022-11-18 10:09 UTC
Labels: duplicate
