### ISSUE TITLE
Crash when atttempting to get foreground color (preview panel)

### ISSUE THREAD

**Issue by leo-arch** [ranger/ranger#2682] opened 2022-07-26 06:52 UTC
#### Runtime Environment

- Operating system and version: archlinux
- Terminal emulator and version: xterm (372), vte (0.28.2)
- Python version: 3.10.5
- Ranger version/commit: 1.9.3 
- Locale: en_US.UTF-8

#### Current Behavior
Ranger crashes when hovering on a plain text file (error getting foreground color for the preview panel)

#### Expected Behavior
No crash

#### Context

This only happens on `xterm` and `vte` (as far as I've tried), and only when **TERM** is set to `xterm` (not happening when set to `xterm-256color`).

#### Possible Solutions
For some reason, the `get_color` function (in `/usr/lib/python3.10/site-packages/ranger/gui/color.py`) is getting values above `curses.COLORS - 1` for `fg` (above 100). `bg` seems to be ok. So, adding this little check (line 31) makes the issue go away:

```py
	if fg > curses.COLORS - 1:
		fg = -1
```
But, of course, this is only a quick hack.

#### Steps to reproduce
1. Run ranger
2. Hover on any plain text file

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8
Current file: '/home/user/Downloads/myfile.txt'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 33, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).
```

**Comment by toonn** [comment] 2022-11-18 10:05
Closing as duplicate of #2498.

**Closed by toonn** 2022-11-18 10:05 UTC
Labels: duplicate
