### ISSUE TITLE
Rifle incorrectly guess MIME type from extension

### ISSUE THREAD

**Issue by desbma** [ranger/ranger#1804] opened 2020-01-06 22:55 UTC
#### Runtime Environment
- Operating system and version: 
`Arch Linux`

- Terminal emulator and version: 
`alacritty 0.4.0`

- Python version / Ranger version/commit / Locale: 
```
ranger version: ranger 1.9.2
Python version: 3.8.1 (default, Dec 21 2019, 20:57:38) [GCC 9.2.0]
```

#### Current Behavior

Rifle identifies Rust language source files (`.rs`) as the MIME type `application/rls-services+xml` which breaks expectations for such files (ie. common Rifle rules to open files with `^text` MIME types with editor).

#### Expected Behavior

A `file` invocation identifies the MIME type as `text/x-c` which is more correct.

#### Possible Solutions

I debugged it to this line:
https://github.com/ranger/ranger/blob/3965e3eeafac8ce44670cfdc25ccc7b5997a3366/ranger/ext/rifle.py#L258

The MIME type is "guessed" from the extension with the `mimetypes` stdlib module, which prevents the `file` program to be invoked.

Solution: Don't rely on the `mimetypes` module, it is incomplete and outdated. 

Also rifle has specific rules for extension matching, so it does not make much sense to ignores the user's choice and rely only on the extension.

**Comment by toonn** [comment] 2020-01-06 23:09
Rifle doesn't ignore anything. It just uses the first matching rule.

I'm sorry but in this case `mimetypes` is right on the money the extension and the media type are [ratified in this RFC](https://tools.ietf.org/html/rfc4826#section-8.2.2).

I suggest you add a file `~/.mime.types` with a line `text/x-rust rs`.
We might consider adding such a line by default, I can imagine more of our users would encounter Rust files than whatever rls-services xmal files are.

**Comment by desbma** [comment] 2020-01-06 23:14
Relying purely on the extension to guess the MIME type is really weird when Rifle has explicit rules to give user the choice to identify files either on the extension or the MIME type.

Anyway, libmagic, and `file` which relies on it, correctly identifies a text file, I guess because it reads the first bytes of the file.

**Comment by toonn** [comment] 2020-01-07 10:52
We switched to the `mimetypes` module because of problems with the `file(1)` approach.

Is it ideal? No. But it's still darn useful. You can't create a rule for "all text files" just using rifle's extension matching.

**Comment by desbma** [comment] 2020-01-07 11:07
> We switched to the mimetypes module because of problems with the file(1) approach.

Out of curiosity, what was that issue?

Also worth noting, is that `scope.sh` reads the MIME type using `file`, so .rs files are previewed as plain text, as expected.

Anyway it's a minor thing, and there are workarounds available, so I wont bother you anymore.



But still, using the `mimetype` module is a bad idea doomed to fail in fire and pain. :wink:

**Comment by toonn** [comment] 2020-01-07 14:00
Feel free to use the issue search functionality. I don't know issue numbers by heart.

**Comment by balroggg** [comment] 2020-08-03 14:54
I have similar issue with opening rust files. Preview works fine.
Edit ends with error when I try to edit rust file
```
ranger            
xdg-open: unexpected option '--'
Try 'xdg-open --help' for more information.
```
OS: Archlinux 
```
uname -a
Linux P55 5.7.11-arch1-1 #1 SMP PREEMPT Wed, 29 Jul 2020 21:38:21 +0000 x86_64 GNU/Linux

ranger --version
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
Locale: en_US.UTF-8
```

I temporary fix this by removing "--" in rifle.conf
```
#-------------------------------------------
# Generic file openers
#-------------------------------------------
label open, has xdg-open = xdg-open "$@"
```
Additional info about mime type:
```
file -i src/lib.rs
src/lib.rs: text/x-c; charset=us-ascii
                                                                                                                              
xdg-mime query filetype src/lib.rs
text/x-c

xdg-mime query default src/lib.rs                                    
```
Any thoughts?

**Comment by toonn** [comment] 2020-08-03 19:18
@balroggg, that issue has been fixed on master. xdg-open doesn't follow the convention that `--` signals the end of options to parse.

**Comment by balroggg** [comment] 2020-08-03 19:41
@toonn Oh I see, thanks for reply!

**Comment by Qwerty-Space** [comment] 2021-01-15 00:39
@vifon @zaeph this is the issue we were talking about in irc.

This issue extends to `sh`, and `json` files which both (incorrectly) report as `application/...` using the mimetypes module.
https://github.com/ahupp/python-magic is a possible alternative, which actually displays it correctly
```python
>>> import magic

>>> f = magic.Magic(mime=True, uncompress=True)
>>> f.from_file("scope.sh")
'text/x-shellscript'
>>> f.from_file("file.json")
'text/plain
```

**Comment by toonn** [comment] 2021-01-15 12:11
The documentation for that library states it's similar to using `file(1)` so that'd probably bring back the issues that originally made ranger switch away from that utility.

**Comment by desbma** [comment] 2021-01-15 12:49
> The documentation for that library states it's similar to using file(1) so that'd probably bring back the issues that originally made ranger switch away from that utility.

I don't know which issues you are referring to, but I don't think that is a good justification for the current behavior, which is ignore the user's choice to use MIME based identification instead of extension based, and to use the inferior `mimetypes.guess_type` for that.

I think we can solve all issues at once, it's not that complicated.

**Comment by toonn** [comment] 2021-01-15 14:44
Feel free to dig through the issue tracker for the issues. I can't remember them. And you'll have to convince us those issues won't simply reappear anyway.

I've wanted to switch back to `file(1}` for years now but noone has the time or motivation to tackle this problem.

**Comment by Qwerty-Space** [comment] 2021-01-15 16:31
> The documentation for that library states it's similar to using `file(1)` so that'd probably bring back the issues that originally made ranger switch away from that utility.

Similar.  Not in the sense that it uses file, but that it returns similar mimetypes.  Why would that bring back the issues?
(Assuming this is the issue you're talking about https://github.com/ranger/ranger/issues/785)

**Comment by toonn** [comment] 2021-01-15 19:19
Both that python module and `file(1)` use libmagic to do what they do. And that's not the issue. It's possible this was straight from hut, not an issue. It's been like this since at least v1.4.0.

**Comment by toonn** [comment] 2021-01-15 19:31
#44 and https://bbs.archlinux.org/viewtopic.php?pid=1147719#p1147719 are relevant.

**Comment by Qwerty-Space** [comment] 2021-01-15 22:59
It would appear there are less issues with `file` than there are python.  And `file` is still [actively maintained](https://bugs.astron.com/view_all_bug_page.php), whereas the `mimetypes` module is not.  It's quite likely the issue is fixed, and if not maybe open an issue on the bug tracker.  

I still think it's worth considering

**Comment by toonn** [comment] 2021-01-15 23:26
I did not say this wouldn't be considered. I've said before I don't like the split between ranger/rifle using mimetypes and scope using `file(1)` (though it also uses mimetypes in one of the commented out cases). But we need *certainty* that it would be an improvement. A *couple* users like the `file(1)` results better but many users either don't care or prefer the mimetypes results.

One of the advantages of the mimetypes module is that it's super simple to override its guesses. Just add a line to `~/.mime.types`, e.g., `text/x-rust rs` would map files with the `.rs` extension to the MIME type `text/x-rust`. `file(1)`'s behavior is harder to override afaik.

Not to mention that libmagic isn't called libmagic for nothing. Determining what programming language a file belongs to is fraught with difficulties and it's basically a coincidence it guesses Rust correctly unless it goes by the file extension.

I don't see why how recent a change was made to mimetypes should reflect on whether or not it's still usable. It's a fairly simple module so little activity probably means there's few bugs. It's part of the python standard library so there's a commitment of maintenance. It also fully adheres to the official MIME types as stipulated by IANA, I don't think you can get more accurate than that.

**Comment by desbma** [comment] 2021-01-16 00:54
> A couple users like the file(1) results better but many users either don't care or prefer the mimetypes results.

You can debate forever about which approach is *most accurate* for the *most* users, but that is so subjective and dependent on one's use case that it won't lead anywhere IMO.

However, some facts that are intangible :
* `rifle.conf` gives the user a way to choose whether to guess from extension or content, the current code disregards that choice, in a way that is confusing and hard to explain unless you look at the code
* the current approach makes you tweaks 3 files (`scope.sh`, `rifle.conf`, and `~/.mime.types`) to get a consistent behavior, with a trial and error approach, that would only be 2 without the `mimetypes` use
* `libmagic`/`file` is used broadly unlike `mimetypes` and  can be considered the de facto, "least surprising" standard for MIME identification on Linux

**Comment by hejops** [comment] 2021-04-07 10:42
I noticed some strange behaviour when I was trying to set up a new rule for plaintext [.gro](https://manual.gromacs.org/archive/5.0.4/online/gro.html) files (`mimetype: text/plain`):

```
mime text, has vmd, X, flag f = vmd "$@"		# A
ext gro, has vmd, X, flag f = vmd "$@"			# B
mime text, ext gro, has vmd, X, flag f = vmd "$@"	# C
-> On their own, none of these three lines are shown on open_with

A + B = A
A + C = A
B + C = B
B + A = B
C + A = C
C + B = C
```

Basically, all three rules seem to work, but the last matching rule is always ignored. The same goes for all six permutations of three lines; the last rule is always ignored. Is this behaviour intended? Maybe there's another rule that I set that causes some kind of conflict?

**Comment by toonn** [comment] 2021-04-07 10:56
I fear this may be due to vifon's off-by-one fix again. This doesn't relate to MIME type guessing, could you open a new issue? Also try to reproduce it using a different extension that doesn't appear in `rifle.conf` yet and detail where in the file you're making the changes.

**Comment by hejops** [comment] 2021-04-07 11:14
Before I make a new issue, would .csv extensions be fine? I recall facing a similar problem when trying to set them up with localc.

**Comment by allgreed** [comment] 2022-12-13 23:36
Not sure if causes are related, but similar behaviour is present when interacting with typescript (as in: programming language) files, which by convention end with `.ts` or `.tsx`. Currently they're recognized as video files. Adding an entry to `.mime.types` seems to solve the issue, but I think this should work out of the box [given typescript's popularity].

Related - my implementation of the fix: https://github.com/allgreed/dotfiles/commit/98674fbe2e027964f19952b712aabbe30b118b73

Os: `NixOS 21.05 (Okapi) x86_64 `
Terminal emulator: `rxvt-unicode (urxvt) v9.26 - released: 2021-05-14`
Ranger:
```
ranger version: ranger 1.9.3
Python version: 3.8.11 (default, Jun 28 2021, 10:57:31) [GCC 10.3.0]
Locale: en_GB.UTF-8
```
I'll also try the fix tomorrow on another OS [Ubuntu, the problem was present on 2 systems].

Please let me know if I should open a new issue, I'll gladly do that.

**Comment by toonn** [comment] 2023-03-06 12:31
@allgreed, thank you for the extra report, I think Typescript is another good candidate for at least being included in our default `.mime.types`.

Meanwhile #2756 is a good example of the kind of mistakes libmagic is prone to.

**Comment by UltraGreed** [comment] 2023-08-22 17:37
As far as I understand, the same problem appears with Haskell files (both .hs and .lhs ext). Workaround with `.mime.types` works, so I guess, it's not worth opening another issue?
```
>>> import mimetypes
>>> mimetypes.guess_type("1.hs")
(None, None)
>>> mimetypes.guess_type("1.lhs")
(None, None)
```
OS: `6.1.38-gentoo x86_64`
Terminal emulator: `alacritty 0.10.1`
```
ranger version: ranger 1.9.3
Python version: 3.11.4 (main, Aug 19 2023, 00:29:01) [GCC 13.1.1 20230527]
Locale: en_US.UTF-8
```

**Closed** 2023-08-23 11:11 UTC
Labels: enhancement
