### ISSUE TITLE
ranger doesn't work inside tmux session

### ISSUE THREAD

**Issue by Awan** [ranger/ranger#2590] opened 2022-03-16 08:21 UTC
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: tmux
- Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0]

- Ranger version/commit: ranger 1.9.3
- Locale: en_US.UTF-8

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/ext/cached_function.py", line 13, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.solarized.Solarized object at 0x7f81f1e12350>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/titlebar.py", line 43, in draw
    self._print_result(self.result)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/titlebar.py", line 152, in _print_result
    self.color(*part.lst)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 73, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/lib/python3.10/site-packages/ranger/ext/cached_function.py", line 15, in inner_cached_function
    value = fnc(*args)
  File "/usr/lib/python3.10/site-packages/ranger/gui/colorscheme.py", line 72, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

```
![image](https://user-images.githubusercontent.com/42554663/158546946-ac04c05e-9a03-41e3-9af1-0d1ec64c2e5b.png)

**Comment by lachokds** [comment] 2022-03-30 18:16
I had the same issue. However, in my case, ranger crashed after I tried opening a `.java` file, giving me a similar traceback:

```
[jonathan@e595~$(pwd)] % ranger
ranger version: ranger 1.9.3
Python version: 3.10.3 (main, Mar 18 2022, 20:27:47) [GCC 11.2.0]
Locale: en_US.UTF-8
Current file: '/home/jonathan/$(pwd)/app/src/main/java/com/.../GlobalApplication.java'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
[jonathan@e595~$(pwd)] %
```

**Comment by CharlesChiuGit** [comment] 2022-06-10 23:11
This seems more like a tmux issue.
In tmux, I can open a toggle terminal in Neovim and call ranger in that toggle terminal. A little slower than calling ranger outside on tmux though.

**Comment by toonn** [comment] 2022-11-18 10:04
Closing as duplicate of #2498.

**Closed by toonn** 2022-11-18 10:04 UTC
Labels: duplicate
