### ISSUE TITLE
How to execute a file from Ranger?

### ISSUE THREAD

**Issue by techmouse** [ranger/ranger#2755] opened 2022-11-30 19:08 UTC
#### Runtime Environment

- Operating system and version: Linux KDE NEON
- Terminal emulator and version: Konsole 22.08.3
- ranger version: ranger 1.9.3
- Python version: 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0]
- Locale: en_US.UTF-8

#### Current Behavior
Nothing.

#### Expected Behavior
File executed.

#### Context
I would like to execute the selected file.

I checked the manual, the keybindings, the settings, the commands, the FAQ, the User Guide, the Arch wiki, Stack Exchange, did a bunch of DuckDuckGo'ing, and even did some Googling in a private window, but found nothing on the matter.

Is it not possible?

#### Possible Solutions
Allow for file executions?

#### Steps to reproduce
1. Select executable file
2. Attempt to execute file

**Comment by gandalf3** [comment] 2022-12-04 02:48
It does seem to be rather hidden, sorry you didn't have any luck! In your rifle.conf, typically in `~/.config/ranger/`, uncomment this line at the bottom; at your own risk of course.

```sh
# The very last action, so that it's never triggered accidentally, is to execute a program:
mime application/x-executable = "$1"
```
(if you don't have a rifle.conf, you can generate the defaults with `ranger --copy-config=rifle`)

You can read more about rifle [here](https://github.com/ranger/ranger/wiki/Official-User-Guide#Rifle) and in its [man page](https://man.archlinux.org/man/rifle.1).

**Comment by techmouse** [comment] 2022-12-04 18:52
> It does seem to be rather hidden, sorry you didn't have any luck! In your rifle.conf, typically in `~/.config/ranger/`, uncomment this line at the bottom; at your own risk of course.
> 
> ```shell
> # The very last action, so that it's never triggered accidentally, is to execute a program:
> mime application/x-executable = "$1"
> ```
> 
> (if you don't have a rifle.conf, you can generate the defaults with `ranger --copy-config=rifle`)
> 
> You can read more about rifle [here](https://github.com/ranger/ranger/wiki/Official-User-Guide#Rifle) and in its [man page](https://man.archlinux.org/man/rifle.1).

Thank you for your reply.

I checked and it looks like that line is _already_ uncommented. So I guess the problem isn't that file execution is disabled. It's that I'm not seeing how to invoke it when I select the file.

Is there a keybinding or something? Or do I type `:execute_command bash` and run it from there?

**Comment by gandalf3** [comment] 2022-12-05 05:46
For me, pressing <kbd>l</kbd> or <kbd>enter</kbd> executes rifle on the currently highlighted file

**Comment by techmouse** [comment] 2022-12-06 19:41
> For me, pressing l or enter executes rifle on the currently highlighted file

Well I tried that and it's still not executing the files. I have no idea what's going wrong.

**Comment by gandalf3** [comment] 2022-12-10 03:03
That is very strange. Is `rifle` in your `$PATH`? Can you execute it on its own, for example `rifle --help`?

**Comment by techmouse** [comment] 2022-12-10 03:58
> That is very strange. Is it only executing which isn't working? For example, does opening files such as images (also with l or enter) work?

It seems so, yes. I haven't tried every file type but everything seems to be opening the selected file with the associated program. The only thing is bash scripts. They're opened with nano, instead of being executed.

But now I'm wondering something else. If I wanted to edit an executable bash script instead of run it, is there a binding to do that instead?

> If not, then is `rifle` in your `$PATH`? Can you execute it on its own, for example `rifle --help`?

It looks like I can run rifle just fine. I didn't realize Ranger made an external call to Rifle.

**Comment by gandalf3** [comment] 2022-12-10 11:34
If you always want to execute scripts, you could remove `sh` from these two lines in your `rifle.conf`:
```
# !mime ^text, label editor, ext xml|json|csv|tex|py|pl|rb|js|sh|php = ${VISUAL:-$EDITOR} -- "$@"
# !mime ^text, label pager,  ext xml|json|csv|tex|py|pl|rb|js|sh|php = "$PAGER" -- "$@"
```
There is the default bindings <kbd>E</kbd> to open with editor, and <kbd>r</kbd> for the open-with menu.

**Comment by toonn** [comment] 2023-03-05 16:24
This seems satisfactorily solved by @gandalf3  (thank you! <3) so I'm gonna close it. Feel free to comment if it's still a problem.

Note that we prefer questions about using Ranger go to either the subreddit, r/ranger, or the IRC channel, #ranger at Libera.Chat.

**Closed by toonn** 2023-03-05 16:24 UTC

**Comment by techmouse** [comment] 2023-03-06 12:31
This is weird. I thought for sure I already responded to this.

Anyhow, @gandalf3 didn't actually solve it. I'm vastly over-summarizing and omitting the smaller points from his post, but he essentially said he doesn't execute files from a file browser. He uses a different method all together to execute files. Which is fine.

But "I don't do things that way" isn't a solution. Again, I'm vastly over-summarizing.

Additionally, I never resolved this. I never found a way to execute files from Ranger. That is, without spawning a shell within Ranger. And even then, that method is way more work than simply using a keyboard shortcut to open a new terminal. And if that's what I wanted, I could have done it at any time. I don't need Ranger for that.

I have since moved on from Ranger so I guess whatever happens is fine, but technically this was never solved. I still can't execute files from within Ranger.

**Comment by toonn** [comment] 2023-03-27 16:35
@techmouse, I'm leaving this closed because I don't think there's a bug here.

The easiest way to check whether it works is to press `r`, that should give you a list of applicable rules and then to press the number associated to that key. It's OK if you've moved on and don't want to spend time on this of course, but if there *is* a real issue it would be good to know.

**Comment by techmouse** [comment] 2023-04-02 22:13
I took another swing at it and I was able to get it working by adding: `label open, has open     = bash -- "$@"` to `rifle.conf` at line 265(for me).

Now when I press `r` and then an option to run the selected file with BASH appears in the list.

If Ranger is supposed to have this functionality by default and mine didn't, then it seems a bug did occur somewhere, even if it was only with the OOB config.

**Comment by toonn** [comment] 2023-04-03 11:02
@techmouse, `has open` only makes sense on macOS, which has a program called `open`.

If your scripts have a proper shebang and are executable then you can use a rule like so `ext sh = "$1"`. The advise earlier in the thread was for binaries rather than scripts. 

Either way, it's not a bug. We have a rule for executing binaries by default but not scripts.
