### ISSUE TITLE
AttributeError when trying to start ranger with a filename as argument

### ISSUE THREAD

**Issue by hubitor** [ranger/ranger#1524] opened 2019-04-08 14:53 UTC
#### Runtime Environment

- Operating system and version: Arch Linux
- Terminal emulator and version: terminator 1.91-6
- Python version: 3.7.3 (default, Mar 26 2019, 21:43:19) [GCC 8.2.1 20181127]
- Ranger version/commit: ranger 1.9.2
- Locale: en_US.UTF-8

#### Current Behavior
I wanted to open a folder with ranger but I accidentally pointed to a file I had just created like this:
$ ranger file

#### Expected Behavior
Inform user that he tried to open a file instead of a folder and then either exit with an error or open normally.

#### Possible Solutions
1. A better error report
2. Ignore user mistake and open ranger normally
#### Steps to reproduce
1. Start ranger like this: $ ranger file

#### Traceback

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/ranger/core/main.py", line 195, in main
    fm.loop()
  File "/usr/lib/python3.7/site-packages/ranger/core/fm.py", line 394, in loop
    ui.redraw()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 339, in redraw
    self.finalize()
  File "/usr/lib/python3.7/site-packages/ranger/gui/ui.py", line 394, in finalize
    DisplayableContainer.finalize(self)
  File "/usr/lib/python3.7/site-packages/ranger/gui/displayable.py", line 264, in finalize
    displayable.finalize()
  File "/usr/lib/python3.7/site-packages/ranger/gui/widgets/view_base.py", line 60, in finalize
    - self.main_column.scroll_begin
AttributeError: 'NoneType' object has no attribute 'pointer'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment] 2019-04-08 18:44
Closing as a duplicate of #1386.

**Closed by toonn** 2019-04-08 18:44 UTC
