### ISSUE TITLE
starting ranger with binding in bash/fish will make ranger stuck after `:bulkrename`

### ISSUE THREAD

**Issue by c02y** [ranger/ranger#2288] opened 2021-03-23 21:25 UTC
#### Runtime Environment

- Operating system and version: Manjaro-Linux
- Terminal emulator and version: xfce4-terminal-v0.8.10, alacritty-v0.7.2, kitty-v0.19.3
- ranger version: ranger-master, manual installation, from latest commit: 5d4b2ce9036380fa769786f748bef5c0c8997ead
- Python version: 3.9.2 (default, Feb 20 2021, 18:40:11) [GCC 10.2.0]
- Locale: en_US.UTF-8

#### Current Behavior

When I bind a key in bash/fish such as `C-g` to start ranger, using default ranger config, select two files, execute `:bulkrename` to rename the files using your `EDITOR`, after saving the result and exiting your editor, the terminal won't return to ranger, it will get stuck with message `Press ENTER to continue` in the terminal, and I have to kill ranger process in another terminal session,  but if I start ranger with typing in the shell prompt, it works fine.

- the ranger config is empty, using the default.
- I've tried with xfce5-terminal, alacritty, kitty
- I've tried `EDITOR` of nano, vim which are terminal editors, and mousepad which is a gui editor, the same result
- If I start ranger with typing in the terminal, it works fine

#### Expected Behavior
After I save the result of editing and exit the editor, `Press ENTER to continue` should return to the normal ranger.

#### Steps to reproduce
1. start bash, `bind -x '"\C-g": ranger'`, start ranger using `C-g` key
2. select two files
3. `:bulkrename` to rename the files
4. save the reault, exit your editor
5. ranger gets stucks, `Press ENTER to continue`  doesn't work as expected

If you are using fish, use `bind \cg ranger`

#### Traceback

```

```

**Comment by toonn** [comment] 2021-03-23 22:19
Probably the same issue as #2287.

**Comment by hownioni** [comment] 2022-08-10 04:08
Im having the exact same problem, it does change the file name but it freezes the program so I have to kill the terminal and enter again.

**Comment by toonn** [comment] 2022-11-21 12:18
Closing as a duplicate of #2287. The issue is most likely due to bracketed paste mode.

**Closed by toonn** 2022-11-21 12:18 UTC
Labels: duplicate
