### ISSUE TITLE
File formats are being parsed as text when extension is unknown

### ISSUE THREAD

**Issue by pete3215** [ranger/ranger#822] opened 2017-03-01 22:42 UTC
#### ISSUE TYPE
- Bug report

#### RUNTIME ENVIRONMENT
- Operating system and version: 
Arch linux

- Terminal emulator and version:
termite v12
 
- Python version: 
3.6

- Ranger version/commit: 
1.8.1

- Locale: 
en

#### EXPECTED BEHAVIOR

None text files should not be parsed with the used settings

#### CURRENT BEHAVIOR

Files like pdf documents are being parsed and shown in the preview when the file extension does not match a know value. If the file test.pdf is renamed test.pdf_ the file is shown as text in the preview

My configuration includes: (all other settings are the default)

set use_preview_script false
set preview_files true
set preview_images false
set preview_directories true
set collapse_preview false

**Comment by nfnty** [comment] 2017-03-01 22:45
Already fixed by 9e2e196b1c090dcfe179132693f68f9638bc1c6b.

**Closed by nfnty** 2017-03-01 22:45 UTC

**Comment by nfnty** [comment] 2017-03-01 22:47
Duplicate of #161.

**Comment by pete3215** [comment] 2017-03-01 22:49
Nice, thanks
