### ISSUE TITLE
Ranger does not open due to KeyError on MacOS

### ISSUE THREAD

**Issue by azzarello** [ranger/ranger#2498] opened 2021-11-22 17:50 UTC
#### Runtime Environment

- Operating system and version: MacOS Big Sur 11.6 20G165
- Terminal emulator and version: iTerm2 3.4.12
- Python version: 3.10.0
- Ranger version/commit: 1.9.3 (from brew)
- Locale: en_US.UTF-8

#### Current Behavior
Doesn't open up `ranger` normally.

#### Expected Behavior
Should open up `ranger` normally.

#### Context

Doesn't work so I cannot use it

#### Possible Solutions
None currently, reinstall from `brew` doesn't work.

#### Steps to reproduce
1.  Just attempted to open `ranger` at the current directory

#### Traceback

```
Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/ext/cached_function.py", line 13, in inner_cached_function
    return cache[args]
KeyError: (<ranger.colorschemes.default.Default object at 0x1063feec0>, 'in_titlebar', 'hostname', 'good')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/titlebar.py", line 43, in draw
    self._print_result(self.result)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/widgets/titlebar.py", line 152, in _print_result
    self.color(*part.lst)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/curses_shortcuts.py", line 73, in color
    attr = self.settings.colorscheme.get_attr(*keys)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/ext/cached_function.py", line 15, in inner_cached_function
    value = fnc(*args)
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/colorscheme.py", line 72, in get_attr
    return attr | color_pair(get_color(fg, bg))
  File "/usr/local/Cellar/ranger/1.9.3_2/libexec/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color pair is greater than COLOR_PAIRS-1 (-1).
```

**Comment by toonn** [comment] 2021-11-23 12:30
I guess curses switched from throwing `curses.error` to throwing a `ValueError` here?

**Comment by seinmon** [comment] 2021-11-23 19:36
I couldn't reproduce the error on (almost) the same environment (macOS Big Sur 11.6.1, iTerm2 3.4.12, Python 3.10, Ranger 1.9.3, None.UTF-8). I didn't try installing from Homebrew, but I tried 3 different downloads (from pip, Macports, and Github source code). All of them worked with no issues.

Did you make any configurations?
Did it stop working, or it was never working? 
Can you also try on the macOS terminal app to see if it runs?
Can you try downloading from a different source (pip, or Github) to see if they work?

**Comment by Liquidmantis** [comment] 2021-12-12 16:28
I'm having this issue, too.  So far it's strictly in tmux with $TERM set to `tmux-256color`.  If I change $TERM to `xterm-256color` it works but I don't know the implications of doing that.  

kitty is my daily driver terminal, but I was able to reproduce the issue in iTerm2 3.4.12 when and only when in tmux.  Same thing, exporting TERM as `xterm-256color` and Ranger works in tmux in iTerm2, too.

**Comment by toonn** [comment] 2022-11-18 13:15
I'm looking for users who are still experiencing this issue and are willing to test #2741.

**Comment by thomasqueirozb** [comment] 2022-11-18 22:30
> I'm looking for users who are still experiencing this issue and are willing to test #2741.

I'm running ranger like this so I can replicate the issue: `TERM=xterm ./ranger.py`
(Note that I'm not on MacOS and commented here since issue #2682 was marked as a duplicate of this one)

It no longer crashes, but the preview of all files is grayed out:

![image](https://user-images.githubusercontent.com/38295417/202813071-01abd1d9-8931-447a-b989-e7698cf39c55.png)

**Comment by cipherdragon** [comment] 2023-01-27 07:59
Had the same issue. Did not try the given fix. Instead I decide to add `ValueError` too to the `except` clause in the `get_color` function. However, I did not do that. Instead I set `TERM` variable to `xterm-256color`, previously it was set to `xterm`.

Now I'm no longer getting this issue.

**Closed** 2023-03-30 12:18 UTC
Labels: bug

**Comment by oyarsa** [comment] 2023-04-06 17:39
Sorry for resuscitating the issue, but this issue wasn't fixed but worked around. `TERM=tmux-256color` is a valid setting and is required to support things like italics. I can alias `ranger` to `TERM=xterm-256color ranger` and it works, but that shouldn't be necessary, should it? 

Ranger should be able to understand that `tmux-256color` is valid and identical to `xterm-256color` for this purposse.

**Comment by toonn** [comment] 2023-04-13 20:03
@oyarsa, so you have a tmux-256color entry under /usr/share/terminfo?

**Comment by oyarsa** [comment] 2023-04-13 20:07
Yes:

<details>

```
❯ infocmp tmux-256color
#	Reconstructed via infocmp from file: /Applications/kitty.app/Contents/Resources/kitty/terminfo/74/tmux-256color
tmux-256color|tmux with 256 colors,
	am, hs, km, mir, msgr, xenl,
	colors#256, cols#80, it#8, lines#24, pairs#0,
	acsc=++\,\,--..00``aaffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
	bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
	clear=\E[H\E[J, cnorm=\E[34h\E[?25h, cr=^M,
	csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
	cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
	cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\EM,
	cvvis=\E[34l, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
	dl=\E[%p1%dM, dl1=\E[M, dsl=\E]0;\007, ed=\E[J, el=\E[K,
	el1=\E[1K, enacs=\E(B\E)0, flash=\Eg, fsl=^G, home=\E[H,
	hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
	il=\E[%p1%dL, il1=\E[L, ind=^J, indn=\E[%p1%dS,
	invis=\E[8m, is2=\E)0, kDC=\E[3;2~, kEND=\E[1;2F,
	kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D, kNXT=\E[6;2~,
	kPRV=\E[5;2~, kRIT=\E[1;2C, kbs=\177, kcbt=\E[Z,
	kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
	kdch1=\E[3~, kend=\E[4~, kf1=\EOP, kf10=\E[21~,
	kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
	kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
	kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
	kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
	kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
	kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
	kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
	kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
	kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
	kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
	kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
	kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
	kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
	kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
	kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
	kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
	kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
	kind=\E[1;2B, kmous=\E[M, knp=\E[6~, kpp=\E[5~,
	kri=\E[1;2A, nel=\EE, op=\E[39;49m, rc=\E8, rev=\E[7m,
	ri=\EM, ritm=\E[23m, rmacs=^O, rmcup=\E[?1049l, rmir=\E[4l,
	rmkx=\E[?1l\E>, rmso=\E[27m, rmul=\E[24m,
	rs2=\Ec\E[?1000l\E[?25h, sc=\E7,
	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
	sgr=\E[0%?%p6%t;1%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p7%t;8%;m%?%p9%t\016%e\017%;,
	sgr0=\E[m\017, sitm=\E[3m, smacs=^N, smcup=\E[?1049h,
	smir=\E[4h, smkx=\E[?1h\E=, smso=\E[7m, smul=\E[4m,
	tbc=\E[3g, tsl=\E]0;, u6=\E[%i%d;%dR, u7=\E[6n,
	u8=\E[?1;2c, u9=\E[c, vpa=\E[%i%p1%dd,
```
</details>

**Comment by oyarsa** [comment] 2023-04-14 11:12
You were right: `/usr/share/terminfo` does not contain the file for `tmux-256color`. How are other programs (`terminal-colors`, `nvim`, `helix`, etc.) picking up this information, then? `infocmp` shows Kitty has it; can `ranger` do the same?

I'm not sure why this happened, but if I use the terminfo from [this gist](https://gist.github.com/nicm/ea9cf3c93f22e0246ec858122d9abea1) instead, `ranger` works as expected.

For reference, the steps are:

```sh
~/tmp 
❯ curl -LOs https://gist.githubusercontent.com/nicm/ea9cf3c93f22e0246ec858122d9abea1/raw/37ae29fc86e88b48dbc8a674478ad3e7a009f357/tmux-256color

~/tmp 
❯ tic -x tmux-256color
```

However, the `tmux-256color` file still isn't present in the `/usr/share/terminfo`, so there's more to it.

**Comment by toonn** [comment] 2023-04-14 19:58
@oyarsa, I believe if infocmp reports on it fine then it's in a good location. (BTW, you should use find or fd to find files, not grep or ripgrep.)
I can't reproduce the issue though. In a tmux session, running `TERM=tmux-256color ./ranger.py` works just fine with the version from the master branch.

**Comment by oyarsa** [comment] 2023-04-14 20:04
Using just `find` I still can't find `tmux-256color`, which I found weird:

```sh
❯ find /usr/share/terminfo/ -type f -name '*256color*'
/usr/share/terminfo//67/gnome-256color
/usr/share/terminfo//45/Eterm-256color
/usr/share/terminfo//73/screen-256color-bce
/usr/share/terminfo//73/screen-256color-bce-s
/usr/share/terminfo//73/screen-256color-s
/usr/share/terminfo//73/screen-256color
/usr/share/terminfo//72/rxvt-256color
/usr/share/terminfo//6b/konsole-256color
/usr/share/terminfo//70/putty-256color
/usr/share/terminfo//78/xterm-256color
/usr/share/terminfo//78/xterm+256color
```

As I mentioned, I imported a different file, and now it works. The weird thing is that every other terminal program worked with the previous file except `ranger`, but that's probably not enough to debug this. Having this issue as a reference is enough.

**Comment by Rom1deTroyes** [comment] 2023-04-15 11:47
Under Debian GNU/Linux :

```sh
❯ locate terminfo | grep tmux
/lib/terminfo/t/tmux
/lib/terminfo/t/tmux-256color
/usr/share/terminfo/t/tmux-direct
/usr/share/terminfo/x/xterm+tmux
```

**Comment by philiprhoades** [comment] 2023-07-27 05:43
I get this error for TERM=xterm on Fedora 38 Sway when I am using kitty but doing this fixes the problem:

export TERM=xterm-kitty
