### ISSUE TITLE
"S" not working

### ISSUE THREAD

**Issue by danieledema** [ranger/ranger#1479] opened 2019-02-17 21:59 UTC
Hi all!
I have an issue with the basic functionalities of Ranger: I cannot run a terminal from within ranger.
Here are more details.

#### Runtime Environment

- Operating system and version: Archlinux
- Terminal emulator and version: bash and fish on alacritty, but I tried termite too and it could not work
- Python version: 3.7.2
- Ranger version/commit: 1.9.2
- Locale: it_IT.UTF8

#### Current Behavior
If you launch ranger from the terminal from folder A, it works as expected and you can move in folder B, where you want a terminal.
If you press "S" (capital), though, it exits with ```Job 1, 'ranger' has stopped``` in the folder I was when I started ranger, A.
if I run ```fg``` twice I get the terminal I wanted (in the ranger folder, B), then I can exit with ctrl-d and ```fg``` again to enter in ranger in the folder I was before, B.

#### Expected Behavior
Give me a terminal.

Thank you very much for your help,
Daniele

**Comment by toonn** [comment] 2019-02-18 14:58
You're gonna have to provide us with a way to reproduce this reliably, cause I can't. Things to try:
  - Does it happen with ranger's master branch?
  - Does it happen when running `ranger --clean`?
  - Does python version matter?
  - Does it happen with xterm?
  - Does it happen in a completely clean VM?
  - Does your locale matter?

Only thing I can think of is maybe your `SHELL` is something exotic or maybe you're pressing `ctrl-z` or something?

**Comment by Vifon** [comment] 2019-02-18 17:33
For what it's worth, I've encountered a similar behavior in some utilities unrelated to ranger, it seems to be a fish bug. I cannot provide much more details though.

**Comment by toonn** [comment] 2019-02-18 18:55
Hmm, then maybe this should be submitted to the fish bug tracker, can't hurt, right?

**Comment by toonn** [comment] 2019-03-21 14:47
Seems to be fixed as of `fish 3.0.2`.

**Closed by toonn** 2019-03-21 14:47 UTC
