### ISSUE TITLE
can't filter in certain directories and with certain patterns 

### ISSUE THREAD

**Issue by charlie39** [ranger/ranger#2659] opened 2022-06-24 13:34 UTC
#### Runtime Environment

- Operating system and version: arch linux 
- Terminal emulator and version: st 0.8.2
- Python version: 3.10.5
- Ranger version/commit: ranger-master 1.9.3.99.g240d8a0e-1
- Locale: LANG=en_US.UTF-8

#### Current Behavior

Can't use filter with certain patterns. In some directories can't filter beyond
a single letter. As soon as i type the second letter or the third in some cases
for the filter pattern, Ranger crashes.

Some other pattern works fine.

The content of a sample directory where i tried filtering and ranger crashes :

```
$ ls

182206.png
2019-08
2019-10
2019-11[BG]
2020-02
ah
asdf
banking
conspiracy.jpg
EMBEDFILE.PNG
iam.svg
iii.png
ii.png
img-2021-10-11-001246.png
img-2021-10-14-234318.png
img-2021-10-16-011948.png
imgr
i.png
Jess
ledhah1.png
ledhah.png
led.png
Memes
originalfile.png
Personal
residential
response
secret
tes.png
tex.png
Trash
Tux.png
Wallpapers
whengoogle-see1.jpg
whengoogle-see.jpg
xclip
zstd-compressed-after-root.png
zstd-compressed-before-root.png
zstd-compressed-home-after.png
zstd-compressed-home-before.png

```
in this directory i can filter with the patterns like ```jpg``` and ```png```
but if use some other random pattern like ```wes``` or any random pattern it
crashes.

#### Expected Behavior
Should be able filter by pattern

#### Context

Without the filter, life is hard
#### Possible Solutions
I haven't gone through the code yet

#### Steps to reproduce
1.  go to any director with bunch of folders and different file formats
2.  run ```:filter jpg```, for example, with the pattern jpg.
3. if it works, try with other patterns. May be patterns that may not have
   matches.

#### Traceback

```

ranger version: ranger-master
Python version: 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0]
Locale: en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python3.10/ranger/core/main.py", line 203, in main
    fm.loop()
  File "/usr/lib/python3.10/ranger/core/fm.py", line 382, in loop
    ui.handle_input()
  File "/usr/lib/python3.10/ranger/gui/ui.py", line 276, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.10/ranger/gui/ui.py", line 206, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.10/ranger/gui/displayable.py", line 272, in press
    focused_obj.press(key)
  File "/usr/lib/python3.10/ranger/gui/widgets/console.py", line 189, in press
    self.type_key(key)
  File "/usr/lib/python3.10/ranger/gui/widgets/console.py", line 218, in type_key
    self.on_line_change()
  File "/usr/lib/python3.10/ranger/gui/widgets/console.py", line 512, in on_line_change
    if cmd and cmd.quick():
  File "/usr/lib/python3.10/ranger/config/commands.py", line 1546, in quick
    self.fm.thisdir.refilter()
  File "/usr/lib/python3.10/ranger/container/directory.py", line 314, in refilter
    self.move_to_obj(self.pointed_obj)
  File "/usr/lib/python3.10/ranger/container/directory.py", line 613, in move_to_obj
    self.load_content_once(schedule=False)
  File "/usr/lib/python3.10/ranger/container/directory.py", line 662, in load_content_once
    self.load_content(*a, **k)
  File "/usr/lib/python3.10/ranger/container/directory.py", line 500, in load_content
    for _ in self.load_generator:
  File "/usr/lib/python3.10/ranger/container/directory.py", line 461, in load_bit_by_bit
    self.correct_pointer()
  File "/usr/lib/python3.10/ranger/container/directory.py", line 655, in correct_pointer
    self.fm.thisfile = self.pointed_obj
  File "/usr/lib/python3.10/ranger/core/fm.py", line 229, in _set_thisfile
    self.thistab.thisfile = obj
  File "/usr/lib/python3.10/ranger/core/tab.py", line 52, in _set_thisfile
    self.fm.signal_emit('move', previous=previous, new=value, tab=self)
  File "/usr/lib/python3.10/ranger/ext/signals.py", line 268, in signal_emit
    fnc(signal)
  File "/usr/lib/python3.10/ranger/core/tab.py", line 40, in _set_thisfile_from_signal
    self.pointer = self.thisdir.pointer
  File "/usr/lib/python3.10/ranger/core/tab.py", line 72, in _set_pointer
    self._pointed_obj = self.thisdir.files[self._pointer]
IndexError: list index out of range

```

**Comment by markus-bauer** [comment] 2022-07-03 11:40
Is this the same as https://github.com/ranger/ranger/issues/2508?

This might be already fixed in the master branch.

**Comment by toonn** [comment] 2022-11-17 13:38
@charlie39, I can't reproduce this and it looks a lot like the linked issue so I'm closing this. If you're still experiencing this problem with the latest ranger from the master branch then you can comment here and I'll reopen.

**Closed by toonn** 2022-11-17 13:38 UTC
