### ISSUE TITLE
not possible to set some option for directories with a given tag

### ISSUE THREAD

**Issue by knezi** [ranger/ranger#828] opened 2017-03-13 10:57 UTC
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Archlinux, x64
- Terminal emulator and version: xterm(327)
- Python version: 3.6.0
- Ranger version/commit: 1.9.0b
- Locale: cs_CZ.UTF8

#### EXPECTED BEHAVIOR

When I type:
`setintag n sort=basename`
Directories tagged with n are really sort by basename, but if I set:
`setintag n preview_directories=False`
Directories tagged with n are still previewed. The same for `preview_files`.

#### STEPS TO REPRODUCE

1. It seems to be independent of platform, so just tag a directory.

**Comment by nfnty** [comment] 2017-03-13 13:51
Duplicate of #207.

**Closed by nfnty** 2017-03-13 13:51 UTC
Labels: bug
