### ISSUE TITLE
Not a very disturbing bug

### ISSUE THREAD

**Issue by RajPorus19** [ranger/ranger#2221] opened 2021-01-10 17:26 UTC
#### Runtime Environment

- Operating system and version: Arch
- Terminal emulator and version: st
- Python version: 3.9.1
- Ranger version/commit:  1.9.3
- Locale: en_US.UTF-8

First of all I want to say that this is not really a very important bug, I was just playing around with the terminal when I found it, I was just curious to find what may cause it, feel free to close this issue if you feel like it's useless !

#### Steps to reproduce
1.  Open Ranger, and open the terminal in whatever folder you want
2. enter "cat $0"
3. watch the letters get corrupted :^)

I find this cool and a nice trick to play on my classmates, they think I am using the terminal in an obscure language..

**Comment by endreszabo** [comment] 2021-02-01 13:56
This is not a bug.

**Comment by toonn** [comment] 2021-02-02 11:23
I can't reproduce this behavior. Does it happen in other terminals?

**Comment by endreszabo** [comment] 2021-02-02 11:58
`cat`ing any binary to the terminal will most probably change its rendering to "graphics" mode. [See this article](https://unix.stackexchange.com/questions/119480/why-and-how-did-using-cat-on-binary-files-mess-up-the-terminal) for more explanation.

**Comment by toonn** [comment] 2021-02-02 15:13
You're right but `$0` seems to be unset for me. `echo $0` doesn't output anything. Maybe that's particular to my shell though.

I'll close the issue to indicate there's not really anything we can do about this.

**Closed by toonn** 2021-02-02 15:13 UTC
