### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by ArchKubi** [ranger/ranger#2540] opened 2021-12-31 18:30 UTC
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime
Invalid linemode: devicons; should be filename/metatitle/permissions/fileinfo/mtime/sizemtime/humanreadablemtime/sizehumanreadablemtime
ranger version: ranger 1.9.3
Python version: 3.10.1 (main, Dec 18 2021, 23:53:45) [GCC 11.1.0]
Locale: en_US.UTF-8
Current file: '/home/archkubi/pythonBlog/index.html'

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.10/site-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.10/site-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3.10/site-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3.10/site-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

#### Runtime Environment

arch linux
cool-retro-term 1.1.1
ranger version: ranger 1.9.3
Python version: 3.10.1
- Locale:

**Comment by chu4ng** [comment] 2022-01-03 20:59
Look at that #2524

**Comment by dzintars** [comment] 2022-01-05 02:16
Same there on a fresh machine.

**Comment by toonn** [comment] 2022-02-27 13:00
Closing this in favor of #2524 because that seems to identify the root cause indeed.

**Closed by toonn** 2022-02-27 13:00 UTC
