### ISSUE TITLE
Crash on rendering text file with special char 

### ISSUE THREAD

**Issue by HumanG33k** [ranger/ranger#2761] opened 2022-12-15 13:07 UTC
#### Runtime Environment

- Operating system and version: Debian testing 
- Terminal emulator and version: 
- Python version: 3.10.9
- Ranger version/commit: 1.9.3
- Locale: fr_FR.UTF-8

#### Current Behavior
crash on the output text file generate https://github.com/D3Ext/AORT and name website.report  

#### Expected Behavior
not crash, render the file 

#### Context
Just explore my files  

#### Steps to reproduce
1. start ranger 
2. go to the file 
3. look the crash 

#### Traceback

```
ranger version: ranger 1.9.3
Python version: 3.10.9 (main, Dec  7 2022, 13:47:07) [GCC 12.2.0]
Locale: fr_FR.UTF-8
Current file: '/home/user/website.report'

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3/dist-packages/ranger/core/fm.py", line 377, in loop
    ui.redraw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 333, in redraw
    self.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/ui.py", line 360, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/displayable.py", line 260, in draw
    displayable.draw()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 187, in draw
    self._draw_file()
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/browsercolumn.py", line 214, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 109, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3/dist-packages/ranger/gui/widgets/pager.py", line 139, in _draw_line
    self.set_fg_bg_attr(*chunk)
  File "/usr/lib/python3/dist-packages/ranger/gui/curses_shortcuts.py", line 89, in set_fg_bg_attr
    self.win.attrset(curses.color_pair(get_color(fg, bg)) | attr)
  File "/usr/lib/python3/dist-packages/ranger/gui/color.py", line 32, in get_color
    curses.init_pair(size, fg, bg)
ValueError: Color number is greater than COLORS-1 (7).

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues

```

**Comment by toonn** [comment] 2023-03-06 12:42
Closing as a likely duplicate of #2752.

**Closed by toonn** 2023-03-06 12:42 UTC
