### ISSUE TITLE
Everything just stop when the preview image is loading

### ISSUE THREAD

**Issue by cain-dev** [ranger/ranger#2808] opened 2023-03-13 00:01 UTC
Every time the cursor is on an image, everything just "stops" until the preview is processed, it looks like the image previewer only does something when the file is selected and Ranger only works again when the file previewer finishes.

(I am using Ranger on the latest version of Arch, but even on Debian or FreeBSD i get the same result)

I was asking remi6397 (on remi6397:feature/sixel)  if they can correct that with sixels image previewer but he suggested me to create a new issue about this.

He said:
"That would be nice, but the directory could be something like an FTP mount (curlftpfs or similar) and we would have no way of knowing that.

It'd however be possible to avoid "stopping the world" by loading the image in background and displaying it asynchronously (unless the selection changed), but I think that'd be a bit awkward to do with Ranger's architecture. Anyhoo, this could be a candidate for another PR. Perhaps open a new issue if nobody requested that before."

My suggestion: 
The previewer process everything inside the directory independently of Ranger selection.
The information is cached.
Ranger shows what is processed (or process something) without influencing (ie stopping) the navigation.

**Comment by toonn** [comment] 2023-03-29 12:47
This is a known issue. Closing in favor of tracking it in #2170.
#2805, which is related to #2502 may improve the situation at least a bit. The problem is no one has come forward to test that change yet!

**Closed by toonn** 2023-03-29 12:47 UTC
