### ISSUE TITLE
ranger crashed. Please report this traceback at: https://github.com/ranger/ranger/issues

### ISSUE THREAD

**Issue by mahpgnaohhnim** [ranger/ranger#1141] opened 2018-04-17 11:16 UTC
#### Runtime Environment

- Operating system and version: Arch Linux (Kernel 4.15.15-1-ARCH) 
- Terminal emulator and version: Termite
- Python version: 3.6.4
- Ranger version/commit: ranger-master 1.9.1 
- Locale: de_DE.UTF-8

#### Traceback

```

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character


```

**Comment by dennisschagt** [comment] 2018-04-24 10:04
Looks like I I got the same error (also using Arch Linux).
When previewing a `desktop.ini` file (in an old Windows backup), ranger crashes with the stack trace shown below.
Running `ranger.py` directly from the master branch does not crash when previewing the same file (on commit a30b5e5b).

```
$ ranger
ranger version: ranger-master 1.9.1
Python version: 3.6.5 (default, Apr 12 2018, 22:45:43) [GCC 7.3.1 20180312]
Locale: en_US.UTF-8
Current file: '[redacted]/desktop.ini'

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 196, in main
    fm.loop()
  File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 390, in loop
    ui.redraw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 338, in redraw
    self.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 365, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 100, in draw
    DisplayableContainer.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 256, in draw
    displayable.draw()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 176, in draw
    self._draw_file()
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 203, in _draw_file
    Pager.draw(self)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 101, in draw
    self._draw_line(i, line)
  File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/pager.py", line 132, in _draw_line
    self.addstr(chunk)
  File "/usr/lib/python3.6/site-packages/ranger/gui/curses_shortcuts.py", line 37, in addstr
    self.win.addstr(*args)
ValueError: embedded null character

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
```

**Comment by toonn** [comment] 2018-04-24 12:49
Is your ranger installed through pacman or aur? If you're running the master branch this shouldn't happen anymore.

**Comment by dennisschagt** [comment] 2018-04-24 12:56
I have it installed via pacman. I can confirm that it is fixed on the master branch.

**Comment by toonn** [comment] 2018-04-24 13:49
:+1:

**Closed by toonn** 2018-04-24 13:49 UTC
