### ISSUE TITLE
terminal width issues in markdown preview

### ISSUE THREAD

**Issue by bnvk** [ranger/ranger#675] opened 2016-09-24 17:02 UTC
I recently discovered a really nifty CLI app written in python that renders pretty 256 colored previews of markdown files called [terminal_markdown_view](https://github.com/axiros/terminal_markdown_viewer). It works by adding to `scope.sh` config file:

```
markdown|md)
try mdv "$path" && { dump | trim; exit 5; } || exit 2;;
```

However, there is a slight bug (which I assume is in module) but whereby Ranger hands off the markdown data which says at the top of every markdown file in the preview pane:

```
!! Could not derive your terminal width !!
```

I want to dig and try to fix / understand where the issue lies exactly, but any help or pointers would be greatly appreciated :smile: perhaps it's just a config setting I need to declare?

**Comment by mrogalski** [comment] 2016-09-24 18:12
The mdv python script has some code that means to recognize the option `-` as stdin (as is the standard in bash).  If the `-` is set, the warning about the terminal width should not be printed, but it doesn't work.  Fix it there, if You want to try and understand their code. 

Anyway, try `try mdv "$path" -c $width && { dump | trim; exit 5; } || exit 2;;` which will set the width of the window for mdv with the `$width` variable that our gracious overlord hut had the prescience to provide.  Alternatively just `grep -v` the offending line.

**Comment by bnvk** [comment] 2016-09-24 18:19
@mrogalski hey thanks so much for the response and tip. I changed to what you suggested, but am still getting the error. Also cross posted on `mdv` repo. 

On a tangent, I wonder what @hut @Vifon stance is on integrating something like `mdv` into the core of ranger, or at very least a suggested tool (like for other preview types).

**Comment by mrogalski** [comment] 2016-09-24 18:39
Maybe try `try cat "$path" | mdv - -c $width && { dump | trim; exit 5; } || exit 2;;`, then?

**Comment by bnvk** [comment] 2016-09-24 23:06
@mrogalski nope, that prevents `mdv` from rendering at all

**Comment by AXGKl** [comment] 2016-09-29 07:06
@mrogalski @bnvk 

Hi, mdv author here: 
1. Ranger seems *really* nice, will include in my tool chain
2. mdv is a two weekend hack, deserves a rewrite given that some people seem to like it 

regarding the width: 

1. I have the bug that I spit out the warning, even if the user calls `mdv` with `-c <columns>` and I'll correct that, removing the warning when -c is set
2. Seems that ranger exports `$width` - and I'll respect that as well, besides the standard `$COLUMNS`. Question: Would the shell's `$LINES` than equal a `$height` in ranger panes?
3. May I sugggest that you (or gracious overlord) export also `$COLUMNS` into the processes rendering the ranger panes, since `$COLUMNS` seems to be the variable used by bash, ksh, zsh on SIGWINCH - so there might be also other tools than mdv checking that?

For @bnvk: A quick fix for now would be to call mdv after exporting COLUMNS and LINES manually, like: `export COLUMNS=$width && export LINES=$height (or e.g. 200 if that is not set in ranger) && mdv "$path"` or make a little wrapper like: 

```
#!/bin/bash
export COLUMNS=$width
export LINES=$height  # or 200

mdv $*
```

which you call in ranger.

**Comment by teranex** [comment] 2017-01-22 20:58
@AXGKl I just discovered mdv through this issue, nice tool! Did you see any chance to fix the issue? With the current version of mdv (pip install) the issue is still present

**Comment by AXGKl** [comment] 2017-01-22 21:08
@teranex : you also get !! Could not derive your terminal width !! ?, is this the issue?

If so: Can you export COLUMNS before calling mdv? mdv does respect $COLUMNS if set, like:

```
~ $ mdv r.md

fooad adf asd fa sdf asdf asdf
  as dfa sdfasd fa sdf as dfa sdf


~ $ export COLUMNS=10; mdv r.md

fooad adf
asd fa sdf
asdf asdf
  as dfa
  sdfasd
  fa sdf
  as dfa
  sdf

```

**Comment by teranex** [comment] 2017-01-22 21:21
@AXGKl I do indeed get the !! Could not derive your terminal width !! inside the preview in Ranger. I use the following code inside my scope.md:

```sh
    markdown|md)
        try mdv "$path" -t 757.2295 -c $width && { dump | trim; exit 5; } || exit 2;;
```

When I run your commands in my shell (ZSH in Terminator) it seems the width is ignored as well:
```sh
mdv r.md
export COLUMNS=10; mdv r.md
export COLUMNS=10 && mdv r.md
COLUMNS=10 mdv r.md
```
All versions are equally long (longest line 98 chars, terminal width 239)

**Comment by AXGKl** [comment] 2017-01-22 21:44
funny, there seems to be really an issue with zsh preventing to overwrite $COLUMNS, resetting it for every process, while bash *is* allowing to overwrite it.
=> I begin to understand why the ranger guys used another variable for user defined terminal width.

Suggestion: Would it help that I first check if $width if set and if so use that?

**Comment by teranex** [comment] 2017-01-22 22:00
When I run `mdv -c 10 r.md` I get correctly wrapped output. I don't really understand why mdv gives a warning about not being able to determine the terminal width (when invoked by ranger) when I explicitly specify the number of columns it should use (through `-c`)? Shouldn't mdv simply use the value for `-c` if it is specified, and only when that is absent then try to determine the terminal width? Or do I misunderstand the issue?

**Comment by AXGKl** [comment] 2017-01-22 22:31
aaah - now I understand. Your problem is "only" the warning allthough you give -c. 

so https://github.com/axiros/terminal_markdown_viewer/commit/9e58f6c630f600320e06c9e455c1baba96940f25#diff-12bfa1d3c822b768d3c25c9f95aa940c and https://github.com/axiros/terminal_markdown_viewer/commit/04debafcb51fd44d3bbce025608a4f694fa718c5  should fix that. stupid me. 

can you confirm?

**Comment by nfnty** [comment] 2017-01-24 10:14
Is this issue resolved?

**Comment by AXGKl** [comment] 2017-01-24 10:24
hi its anyway no ranger issue => you can close it here.  

@teranex : open an issue at the mdv repo if you still have problems.

**Comment by nfnty** [comment] 2017-01-24 10:26
Alright, thanks.

**Closed by nfnty** 2017-01-24 10:26 UTC
Labels: image-preview, question, waiting

**Comment by teranex** [comment] 2017-01-24 19:55
@AXGKl the above patches fix the warning indeed. Thx!

**Comment by AXGKl** [comment] 2017-01-25 09:30
@teranex : I'm also respecting $width now with precedence over $COLUMNS (which zsh seems to want to control) - so I hope in ranger the width is now fitting w/o the need to set it manually.

**Comment by teranex** [comment] 2017-01-25 11:49
@AXGKl when I run mdv without `-c $width` the lines are longer than the preview area. But when I use `-c $width` it works for me, so no problem for me. Thx
