### ISSUE TITLE
Ranger crashes when deleting to Trash

### ISSUE THREAD

**Issue by w2kpro** [ranger/ranger#1798] opened 2019-12-30 13:03 UTC
OS: Linuxmint 19.3
Python: 3.6.9
Ranger: v1.9.2
trash-cli: 0.12.9.14-2.1

When deleting a highlighted file to trash, I get the following error:
"object has no attribute 'path'"

When deleting a (one) selected file to trash, I am asked to confirm delete, and after inputing 'y' ranger crashes.
----------------------------------------------------------------------
ranger version: ranger-master
Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
Locale: en_GB.UTF-8
Current file: '/home/standard_user/file.txt'

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/ui.py", line 279, in handle_input
    self.handle_key(key)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/ui.py", line 209, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/displayable.py", line 271, in press
    focused_obj.press(key)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/lib/python3.6/dist-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/lib/python3.6/dist-packages/ranger/config/commands.py", line 757, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/actions.py", line 458, in execute_file
    filenames = [f.path for f in files]
  File "/usr/local/lib/python3.6/dist-packages/ranger/core/actions.py", line 458, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'

ranger crashed. Please report this traceback at:
https://github.com/ranger/ranger/issues
------------------------------------------------------------

    Thank you for contributing to ranger by opening this issue.
    Please check through this list, so you can be as helpful as possible:

    1. Was this issue already reported?  Please do a quick search.
    2. Maybe the problem is solved in the current master branch already?
       Simply clone ranger's git repository and run ./ranger.py to find out.
    3. Provide all the relevant information, as outlined in this template.
       Feel free to remove any sections you don't need.
-->

#### Runtime Environment

- Operating system and version: 
- Terminal emulator and version: 
- Python version: 
- Ranger version/commit: 
- Locale: 

#### Steps to reproduce
1. 
2. 
3. 

#### Traceback

```

```

**Comment by toonn** [comment] 2019-12-30 16:35
How did you invoke the trash command?

**Comment by magnetophon** [comment] 2020-01-07 13:59
I'm having the same issue with 1.9.2.
This is what I did: nothing marked, put cursor on file, hit dT, hit enter, confirm with y  -> crash

**Comment by w2kpro** [comment] 2020-01-08 12:32
Just compiled v1.9.3 and get the same crash as above. Also, "open_with" key 'r', no longer works!

**Comment by toonn** [comment] 2020-01-08 21:53
@w2kpro, this is a confirmed bug yes. Wasn't labeled because of oversight. However, I can't reproduce your problem with the `r` keybinding. Please open a separate issue on that if you can reproduce it when running `ranger --clean`.

**Comment by iharsuvorau** [comment] 2020-02-02 19:08
Crashes while trying to trash a directory. Steps to reproduce:

- mark a dir with `space`
- `d`
- `T`
- `enter`
- `y`

```
ranger version: ranger 1.9.3
Python version: 2.7.16 (default, Nov  9 2019, 05:55:08) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
Locale: None.None
Current file: '/Users/ihar/projects/bahna cms/devel/editor/testdata/fooSite/content/en/wetland/ru/bolota'

Traceback (most recent call last):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/local/Cellar/ranger/1.9.3/libexec/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'
```

**Comment by xuelvming** [comment] 2020-02-17 00:34
Yep, Got the same issue here in mac , installed through homebrew

```bash
brew info ranger
ranger: stable 1.9.3, HEAD
File browser
https://ranger.github.io
/usr/local/Cellar/ranger/1.9.3 (187 files, 1.4MB) *
  Built from source on 2020-02-16 at 19:38:42
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/ranger.rb
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 2,645 (30 days), 8,257 (90 days), 20,879 (365 days)
install-on-request: 2,552 (30 days), 7,956 (90 days), 20,366 (365 days)
build-error: 0 (30 days)
```

**Comment by Augists** [comment] 2020-05-14 16:23
So why closed?
It only occurs on mac?
I have to throw away my `dT`...:(
There **IS** a bug

**Comment by toonn** [comment] 2020-05-14 19:54
@Augists, I closed your issue because this one is the same problem. No need to track it in multiple threads, just gets confusing.

**Comment by salkin-mada** [comment] 2020-08-17 20:41
have it here too it seems
```
ranger version: ranger 1.9.3
Python version: 3.8.5 (default, Jul 27 2020, 08:42:51) [GCC 10.1.0]
Locale: en_DK.UTF-8
Current file: '/home/salkin/Downloads/FNET-master.zip'

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/ranger/core/main.py", line 201, in main
    fm.loop()
  File "/usr/lib/python3.8/site-packages/ranger/core/fm.py", line 383, in loop
    ui.handle_input()
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 266, in handle_input
    self.handle_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/ui.py", line 196, in handle_key
    elif not DisplayableContainer.press(self, key):
  File "/usr/lib/python3.8/site-packages/ranger/gui/displayable.py", line 275, in press
    focused_obj.press(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 188, in press
    self.type_key(key)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 214, in type_key
    self._answer_question(answer)
  File "/usr/lib/python3.8/site-packages/ranger/gui/widgets/console.py", line 197, in _answer_question
    callback(answer)
  File "/usr/lib/python3.8/site-packages/ranger/config/commands.py", line 759, in _question_callback
    self.fm.execute_file(files, label='trash')
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in execute_file
    filenames = [f.path for f in files]
  File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
AttributeError: 'str' object has no attribute 'path'
```

**Comment by magnetophon** [comment] 2020-08-17 21:58
@salkin-mada Please read [the comment efore yours](https://github.com/ranger/ranger/issues/1798#issuecomment-628853963)

**Comment by salkin-mada** [comment] 2020-08-18 05:56
Hi @magnetophon I did. Maybe I am mistaking but it references that #2050 was closed in favor of this issue #1798 ?

**Comment by toonn** [comment] 2020-08-18 06:45
Yep, to be clear, THIS is the open/active issue.

**Comment by magnetophon** [comment] 2020-08-18 08:11
@salkin-mada Hmm, I didn't read properly, yet told you to read... Sorry.

**Comment by AXGKl** [comment] 2021-03-23 22:14
until fixed here a hack which works for me:

```python
File "/usr/lib/python3.8/site-packages/ranger/core/actions.py", line 459, in <listcomp>
    filenames = [f.path for f in files]
```
change the line to 

```python
   filenames = [f if isinstance(f, str) else f.path for f in files]
```
Use at your own risk though, no guarantees.

**Closed** 2021-03-28 19:02 UTC
Labels: bug
