### ISSUE TITLE
ranger crash when viewing linemode fileinfo

### ISSUE THREAD

**Issue by vijaygopal1234** [ranger/ranger#973] opened 2017-11-12 02:24 UTC
#### ISSUE TYPE

- Bug report

#### RUNTIME ENVIRONMENT

- Operating system and version: Manjaro - latest
- Terminal emulator and version: Tilix 1.7.1
- Python version: 3.6.3
- Ranger version/commit: ranger-stable 1.8.1
- Locale: en_US.UTF-8

#### EXPECTED BEHAVIOR

Show lineinfo

#### CURRENT BEHAVIOR

Crashes 

#### CONTEXT

Trying to view fileinfo in a directory with more than 5 files. 100% reproducible.

#### STEPS TO REPRODUCE

1. Go a directory with more than 5 files 
2. Press Mi

#### TRACEBACK

```
ranger version: 1.8.1, executed with python 3.6.3
Locale: en_US.UTF-8
Current file: REDACTED
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/ranger/core/main.py", line 145, in main
fm.loop()
File "/usr/lib/python3.6/site-packages/ranger/core/fm.py", line 362, in loop
ui.redraw()
File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 295, in redraw
self.draw()
File "/usr/lib/python3.6/site-packages/ranger/gui/ui.py", line 322, in draw
DisplayableContainer.draw(self)
File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
displayable.draw()
File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/view_miller.py", line 99, in draw
DisplayableContainer.draw(self)
File "/usr/lib/python3.6/site-packages/ranger/gui/displayable.py", line 248, in draw
displayable.draw()
File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 168, in draw
self._draw_directory()
File "/usr/lib/python3.6/site-packages/ranger/gui/widgets/browsercolumn.py", line 348, in _draw_directory
infostringdata = current_linemode.infostring(drawn, metadata)
File "/usr/lib/python3.6/site-packages/ranger/core/linemode.py", line 107, in infostring
fileinfo = fileinfo.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'

ranger crashed.  Please report this traceback at:
https://github.com/hut/ranger/issues
```

**Comment by plmuon** [comment] 2018-01-28 20:43
Same here on arch as of 28.01.2018. Locale en_GB.UTF-8.

**Comment by toonn** [comment] 2018-01-28 21:17
Can't reproduce this with ranger `1.9.0b5`, `python 3.6.4`. A new version has just been released so please report back after that gets to arch/manjaro.

**Comment by plmuon** [comment] 2018-01-29 19:00
Indeed, today arch upgraded to 1.9.0, the problem has been fixed.

**Comment by toonn** [comment] 2018-01-30 00:41
Thanks for reporting back I'm closing this for now, feel free to mention me or open a new issue if this hasn't been fixed for you.

**Closed by toonn** 2018-01-30 00:41 UTC
