### ISSUE TITLE
ranger hangs during start-up inside tmux but starts fine outside

### ISSUE THREAD

**Issue by v0lker** [ranger/ranger#2452] opened 2021-09-16 20:09 UTC
#### Runtime Environment

- Operating system and version: macOS 10.14
- Terminal emulator and version: iterm 3.3.2, tmux 3.2a
- Python version: 3.9.7
- Ranger version/commit: 1.9.3
- Locale: en_GB.UTF-8

#### Current Behavior
starting inside tmux (inside iTerm), where TERM=screen-256color, it hangs at ```loading...```, doesn't react to ^C, but to ^\

starting directly inside iTerm), where TERM=xterm-256color, it starts ok.

i tried other values for TERM and other terminal emulators (xterm, Terminal) to no avail.

ncurses is 6.2_1 (via macports)

#### Expected Behavior
successful start inside tmux as well as outside

#### Steps to reproduce
1. start ranger
2. 
3. 

#### Traceback

```

```

**Comment by v0lker** [comment] 2021-09-16 20:18
starting a new tmux session resolved the issue. i couldn't repro this since.

**Comment by toonn** [comment] 2021-09-17 11:21
Since it's not reproducible and this code has been changed on master I'm going to close this. If you experience the issue on the master branch or find a way to reproduce it, we can reopen.

**Closed by toonn** 2021-09-17 11:21 UTC
